### ISSUE TITLE
User can't SSH into container due to MTU

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#1052]
On client lowering MTU fixed the problem with SSH.

**Comment by crioto** [comment]
This issue can be solved in two different ways:

- Enabling PMTU in daemon
- Lowering MTU value

Both options needs to be supported by p2p configuration file and in Control Centel configuration window (subutai-io/control-center#1638). Windows version doesn't support Configuration yet (#1068) and Linux package doesn't properly deliver configuration file (#1069).

**Comment by kurmanbekova6** [comment]
Followed the steps described above:
Result: 
On Mac OS: Environment's state switching between initializing and connecting.
On Linux: Environment's state switching between initializing, connecting, ready.
![screenshot from 2018-12-07 15-35-25](https://user-images.githubusercontent.com/9501291/49639656-bd3e7d80-fa35-11e8-96b4-46866eb0ba61.png)

**Comment by kurmanbekova6** [comment]
Set  `pmtu:true` and restarted p2p daemon
![screenshot_41](https://user-images.githubusercontent.com/9501291/49710329-7f845500-fbed-11e8-8b05-e42244c2ead7.png)
Environment's state switching on all OSs.

**Comment by crioto** [comment]
@kurmanbekova6 can you show your `p2p debug` please? Also, what happens if you don't set pmtu to true?

**Comment by kurmanbekova6** [comment]
On windows when **pmtu: true**, p2p periodically disconnecting and reconnecting.
![screenshot_1](https://user-images.githubusercontent.com/9501291/49847226-e2a7f000-fd83-11e8-966a-6af0e28695f4.png)
![screenshot_2](https://user-images.githubusercontent.com/9501291/49847230-e3d91d00-fd83-11e8-8717-50bac763bfc7.png)
**pmtu:false**
![screenshot_3](https://user-images.githubusercontent.com/9501291/49847285-31ee2080-fd84-11e8-8364-67069fa4d41d.png)

**On Mac:**
**pmtu:true**
<img width="623" alt="screen shot 2018-12-12 at 10 03 22 am" src="https://user-images.githubusercontent.com/9501291/49847339-6feb4480-fd84-11e8-9c82-a5783fb96586.png">
**pmtu:false**
<img width="617" alt="screen shot 2018-12-12 at 10 07 53 am" src="https://user-images.githubusercontent.com/9501291/49847338-6eba1780-fd84-11e8-89c3-9fe239c1cfba.png">

On Linux:
About 40~50 min environments state switching and becoming stable.



[pmtu_false_mac.zip](https://github.com/subutai-io/p2p/files/2670485/pmtu_false_mac.zip)

**Comment by kurmanbekova6** [comment]
**set pmtu to true**
On Mac OS:
Environments state stable, did not switch.
ssh to container works as well
<img width="616" alt="screen shot 2018-12-14 at 9 57 02 am" src="https://user-images.githubusercontent.com/9501291/49982684-bc648a80-ff12-11e8-8479-046f4b7bd6f6.png">
On Linux:
Environments state stable, did not switch.
ssh to container works
On Windows:
Environments state stable.
Can't ssh to container
![screenshot_4](https://user-images.githubusercontent.com/9501291/49983142-b58b4700-ff15-11e8-86c5-92c473f63749.png)
Will attach logs from windows after 30 min

**Comment by kurmanbekova6** [comment]
On windows: 
![capture](https://user-images.githubusercontent.com/9501291/49992073-de243880-ff37-11e8-9234-c1219d9734f9.PNG)

**Comment by kurmanbekova6** [comment]
On Mac and on Linux works fine. Environment's state stable on all OS's. 
Сan't ssh, if `pmtu true` on all windows. 
[ipconfig.zip](https://github.com/subutai-io/p2p/files/2694242/ipconfig.zip)

**Comment by kurmanbekova6** [comment]
![capture](https://user-images.githubusercontent.com/9501291/50264630-5c695a80-03d0-11e9-8dae-bafc84e2be13.PNG)
Connected to container via ssh
Tested in master

**Comment by kurmanbekova6** [comment]
**On Linux:** 
![screenshot from 2018-12-21 12-28-51](https://user-images.githubusercontent.com/9501291/50328135-2cc76900-051c-11e9-8f49-355f8594f465.png)
![screenshot from 2018-12-21 12-29-42](https://user-images.githubusercontent.com/9501291/50328136-2d5fff80-051c-11e9-8899-08e2730b2567.png)
