### ISSUE TITLE
Use uuid implementation from Google

### ISSUE THREAD

**Issue by happyaron** [subutai-io/p2p#1057]
p2p makes use of uuid library github.com/wayn3h0/go-uuid, which is deprecated and moved to github.com/golang-plus/uuid. But after some search there appears to be many uuid implementations and the most popular one is from Google: https://github.com/google/uuid

Would you mind to use this implementation, instead of the existing one? So that we have fewer rarely used dependency for Debian inclusion. I understand the API is incompatible, but greping p2p source tree shows that it only uses the library to generate a time-based UUID value, which might not too hard to replace.

**Comment by crioto** [comment]
In [dev](/subutai-io/p2p/tree/dev) with #1060

**Comment by crioto** [comment]
Released in 353f8b5
