### ISSUE TITLE
Add configuration support on Windows

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#1068]
In order to support PMTU and MTU values on Windows, we need to provide configuration support on Windows with default configuration file delivered by MSI package.

**Comment by crioto** [comment]
Reinstall from package(sic!) is required!

**Comment by kurmanbekova6** [comment]
![screenshot_39](https://user-images.githubusercontent.com/9501291/49637205-96426600-f9b9-11e8-8a92-81086afa71e3.png)
There is no p2p.yaml file

**Comment by crioto** [comment]
Correct, some problem with devops for windows. I'll work on a fix on Monday

**Comment by crioto** [comment]
Devops for master fixed. Please, try again

**Comment by kurmanbekova6** [comment]
Tested in master
![screenshot_40](https://user-images.githubusercontent.com/9501291/49709385-df2c3180-fbe8-11e8-859c-909cb215123f.png)

**Comment by kurmanbekova6** [comment]
![screenshot_7](https://user-images.githubusercontent.com/9501291/50326907-ea4f5d80-0516-11e9-8cb2-c7ec117b1c23.png)
Tested in prod
