### ISSUE TITLE
Deliver configuration file when installing on Linux and Darwin

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#1069]
In order to configure PMTU and MTU values on Linux we need to deliver configuration file inside Debian package, so Control Center will be able to alter p2p behaviour

**Comment by crioto** [comment]
On linux: `/etc/p2p.yaml`
On macos: `/Applications/Subutai.P2P/Contents/Resources/p2p.yaml`
Reinstall from package(sic!) is required!

**Comment by kurmanbekova6** [comment]
On Linux:
![screenshot from 2018-12-07 14-30-55](https://user-images.githubusercontent.com/9501291/49636883-15718180-fa2e-11e8-96f4-a9ac37a8680b.png)

**Comment by kurmanbekova6** [comment]
On Mac OS:
<img width="247" alt="screen shot 2018-12-07 at 2 57 29 pm" src="https://user-images.githubusercontent.com/9501291/49637760-84e87080-fa30-11e8-83a0-bda4c8ab930f.png">
Fixed in master

**Comment by kurmanbekova6** [comment]
<img width="211" alt="screen shot 2018-12-21 at 12 01 59 pm" src="https://user-images.githubusercontent.com/9501291/50327222-60a08f80-0518-11e9-971b-0396d1d731a0.png">
