### ISSUE TITLE
Generating feedback from update processes 

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/p2p#1075]
Alex's post from Slack:
`All projects that are associated with building packages and have postinstall scripts should be made to log with extremely high verbosity. They should check before doing some operation for the right conditions before doing it, and report. Then they should do the operation and log the success or failure and error messages. They should then do a check that everything is fine before continuing to the next step. These package postinstall scripts are short lived (they do their thing then die). It's OK to have them be extremely verbose in their logging output so we can capture upgrade problems and fix them. Right now the upgrade process is a black box for us. Let's change this.`

**Comment by crioto** [comment]
After latest update of the debian package we don't use postinstall scripts anywhere in p2p, so it's not possible to get any extra feedback from installation process.
