### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [subutai-io/p2p#1077]
i've downloaded Version '7.1.0' but when selecting it in the Finder and using 'Get Info' it shows Version '0.01'

 i guess the **CFBundleVersion** and **CFShortVersionString** entries in your **Info.plist** file are wrong.
all apps on macOS are supposed to contain valid version information.

**Comment by crioto** [comment]
@core-code Thank you. This will be fixed in the next release.

**Comment by core-code** [comment]
awesome, thanks

**Comment by kurmanbekova6** [comment]
Downloaded and installed p2p.
Checked version of p2p. 

_Version: Subutai p2p_
![screen shot 2018-10-03 at 10 03 20 am](https://user-images.githubusercontent.com/9501291/46389457-be92a900-c686-11e8-9bcf-608e236209c9.png)

**Comment by kurmanbekova6** [comment]
Shows exact version

_Version: 7.1.1-master_
![screen shot 2018-10-03 at 12 45 59 pm](https://user-images.githubusercontent.com/9501291/46394274-792da600-c69d-11e8-89f4-7c49e87840ef.png)

Fixed on Master

**Comment by core-code** [comment]
thanks

**Comment by crioto** [comment]
Thank you @core-code @kurmanbekova6
