### ISSUE TITLE
Retry to get IP multiple times during start up process

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#1095]
During creation of p2p instance we can request IP from DHT instead of specifying one manually (used by clients/CC). We want this request to be sent multiple times before giving up on the process.

**Comment by kurmanbekova6** [comment]
DHT was restarted 2 times. Environments did not fail.
Restarted p2p on client, environments after some time became healthy.
Fixed in Master.

**Comment by kurmanbekova6** [comment]
DHT was restarted several times. Environments did not fail.
Fixed in prod.
