### ISSUE TITLE
Output error messages to stderr instead of stdout

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#1102]
Review all error output messages and find ones, that go to stdout and redirect them to stderr instead.

**Comment by kurmanbekova6** [comment]
Tested in master
![screen shot 2018-11-01 at 10 26 23](https://user-images.githubusercontent.com/9501291/47832766-7966b180-ddc1-11e8-8567-d28bcb29b3fb.png)

**Comment by kurmanbekova6** [comment]
prod p2p:
![screen shot 2018-11-07 at 15 44 50](https://user-images.githubusercontent.com/9501291/48123422-11720880-e2a4-11e8-9560-03e2deec7514.png)
Tested in prod
