### ISSUE TITLE
Support YAML for dump file

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#1105]
We want to start using YAML formatted dump file for easy save/load of p2p instances. For back compatibility we will continue to support old version of save file.

**Comment by kurmanbekova6** [comment]
prod peer: 
![screen shot 2018-11-07 at 15 13 19](https://user-images.githubusercontent.com/9501291/48121699-d241b880-e29f-11e8-9490-228eb4be5f5a.png)
Fixed in prod.
