### ISSUE TITLE
IP address reconfiguration on Windows

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#1124]
We need to test if IP address reconfiguration is possible on Windows OS. If it's possible to configure IP address multiple times with an active interface, then we can implement this feature for `auto` IP configuration.

**Comment by crioto** [comment]
I've implemented new option for `set` command: `--ip`. You can specify new interface IP using this option in a combination with `--hash`. This needs to be tested.

**Comment by crioto** [comment]
Automatic configuration was tested on Windows and macOS and it works with no issues.

**Comment by kurmanbekova6** [comment]
![screen shot 2018-12-27 at 11 35 03](https://user-images.githubusercontent.com/9501291/50467180-ef575580-09cb-11e9-8d07-983a43c7dd20.png)
![screen shot 2018-12-27 at 11 59 12](https://user-images.githubusercontent.com/9501291/50467705-86251180-09ce-11e9-850f-aea2cfb9a17f.png)
