### ISSUE TITLE
IP address reconfiguration on MacOS

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#1125]
We need to test if IP address reconfiguration is possible on MacOS. If it's possible to configure IP address multiple times with an active interface, then we can implement this feature for `auto` IP configuration.

**Comment by crioto** [comment]
I've successfully implemented IP reconfiguration using `set` command

**Comment by kurmanbekova6** [comment]
![screen shot 2018-12-27 at 12 06 14](https://user-images.githubusercontent.com/9501291/50467908-7954ed80-09cf-11e9-8ecb-10336aa2d14b.png)
@crioto  Can you please guide me how can I test this issue? I think I did it wrong at above screenshot.

**Comment by crioto** [comment]
After you started your env just run p2p set -ip 10.10.100.100 and check if that up was set using ifconfig command

**Comment by kurmanbekova6** [comment]
![screen shot 2018-12-28 at 15 46 52](https://user-images.githubusercontent.com/9501291/50511355-88af6600-0ab7-11e9-86d9-7b894bb2f901.png)
Tested in prod.
