### ISSUE TITLE
Control Center peer builder support for macOS BigSur 11.1 (move to cc project)

### ISSUE THREAD

**Issue by sapurai** [subutai-io/p2p#1234]
* What's your Operating System? 
macOS Big Sur 11.1

* Describe your problem and steps to reproduce it
I have installed Subutai Control Center and all Components. When trying to create a peer the process finishes and simply closes without any result. No peers created.

* Show output of `p2p debug`
Version: 8.3.1 Build: 8.3.1
Uptime: 0 h 14 m 17 s
Number of gouroutines: 11
PMTU: Disabled
Bootstrap nodes information:
  62.138.0.225:6881 Rx: 788 Tx: 0 Version: 8.1.5 Packet version: 20005
Instances information:

**Comment by akarasulu** [comment]
Unfortunately, we do not support BigSur for peer building functionality in SCC right now. I don't think anyone in the community is that brave enough yet to move to BigSur :-) ... I'm still on Mojave after a Catalina upgrade bricked one of my other Macs.

However, as a workaround, we advise using the hardcore admin approach versus the control center UI to set up your own peer. Control-center installs a hypervisor as you can see and sets up a peer for you. But it is always better to do it manually if you can deal with the directions here: https://docs.subutai.io/working-with-subutai/using-peeros/peeros-advanced-install. You can follow those instructions on a VM running a fresh Debian 10 server. Should be straightforward, and if you run into problems just ping us here or in slack.

**Comment by akarasulu** [comment]
@crioto guess we need to move this over to [control-center](https://github.com/subutai-io/control-center) and get our hands on a BigSur machine ...

**Comment by crioto** [comment]
Thank you, @akarasulu and thank you @sapurai for your report

We will start working on BigSur support for peer creation in the nearest future.
