### ISSUE TITLE
Can not ping container from host, can not ssh

### ISSUE THREAD

**Issue by btemir** [subutai-io/p2p#144]
Installations on Ubintu-VMWare-Win, Windows-VMWare-Win: can not ping container from host, can not ping hoist from RH
![about](https://cloud.githubusercontent.com/assets/16958983/15772262/307b4cca-2981-11e6-9744-0ba15caf1946.PNG)
[karaflogs2016-06-03 10-39-26.txt](https://github.com/subutai-io/p2p/files/297137/karaflogs2016-06-03.10-39-26.txt)
[error_03.06.2016.txt](https://github.com/subutai-io/p2p/files/297138/error_03.06.2016.txt)
[info_03.06.2016.txt](https://github.com/subutai-io/p2p/files/297139/info_03.06.2016.txt)
![image](https://cloud.githubusercontent.com/assets/16958983/15772307/724a813e-2981-11e6-98e4-a434683106aa.png)
![image](https://cloud.githubusercontent.com/assets/16958983/15772340/a2d824a0-2981-11e6-89cf-9665a3e86921.png)

journalctl -u *p2p* shows nothing

[p2p_log.txt](https://github.com/subutai-io/p2p/files/297150/p2p_log.txt)

**Comment by btemir** [comment]
![image](https://cloud.githubusercontent.com/assets/16958983/15772611/1600bf40-2983-11e6-8bbc-cd9ede19f4ef.png)
 
![image](https://cloud.githubusercontent.com/assets/16958983/15772632/361d6a76-2983-11e6-8f58-ca1e3960ceba.png)

**Comment by crioto** [comment]
@btemir p2p.exe has been updated and uploaded to a CDN. Testing is required

**Comment by crioto** [comment]
This issue is outdated
