### ISSUE TITLE
P2P daemon crashes.

### ISSUE THREAD

**Issue by Lezh1k** [subutai-io/p2p#147]
1. Run p2p daemon
2. Launch 2 terminals.
3. Launch in each terminal start command with ip = "dhcp"  (try to join to existing swarm). 
4. See crash report. Reproduces everytime. As we know this issue related to not thread-safe map.

**Comment by crioto** [comment]
Reproduced. Applying fixes

**Comment by Lezh1k** [comment]
Fixed
