### ISSUE TITLE
[Installer Windows 10] Can not get access into container

### ISSUE THREAD

**Issue by absidish** [subutai-io/p2p#152]
Test case:
1) Create env with any template.
2) After ready status try ssh into container.
Result: Connection time out.

![3](https://cloud.githubusercontent.com/assets/8696139/16071356/ac6b6a20-32fc-11e6-9474-c5378f67661c.png)

![1](https://cloud.githubusercontent.com/assets/8696139/16071365/c1ea1702-32fc-11e6-980d-37c8e0bb2eca.png)

**Comment by akarasulu** [comment]
@crioto @Lezh1k any ideas what's happening?

**Comment by absidish** [comment]
Could not reproduce on Windows 10. Will test with Windows 7,8.

**Comment by Lezh1k** [comment]
Need more details. 
Need logs, need errors. Need p2p debug and p2p show outputs.

**Comment by crioto** [comment]
This issue was fixed in the latest updates
