### ISSUE TITLE
Ping works always, but SSH does not 

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/p2p#153]
I created env using 3 peers: 
* Askat Peer (behind NAT)
* Sydyk Peer (behind NAT)
* AWS Germany (accessible directly)

![image](https://cloud.githubusercontent.com/assets/7465404/16173400/03caf08e-35c2-11e6-800b-db6d5c8f72d6.png)

I can successfully ping containers to each other (see ping-ssh-check.txt). But SSH fails between them (askat-peer-p2p-logs.txt). Seems this issue is mostly between peers behind NAT.

Note: for each command's response I waited ~20 sec. If there was none I typed Ctrl-C.

[ping-ssh-check.txt](https://github.com/subutai-io/p2p/files/321950/ping-ssh-check.txt)
[askat-peer-p2p-logs.txt](https://github.com/subutai-io/p2p/files/321949/askat-peer-p2p-logs.txt)

**Comment by asanaliev** [comment]
I tested a second time. As before, from AskatPeer to SydykPeer two SSH commands completed successfuly, two others failed. 
```
root@2c86b132-1f04-467d-932f-14a732cfd61f:/# ssh root@172.29.73.3 date
^C
root@2c86b132-1f04-467d-932f-14a732cfd61f:/# ssh root@172.29.73.3 date
Sat Jun 18 23:16:47 EEST 2016
root@2c86b132-1f04-467d-932f-14a732cfd61f:/# ssh root@172.29.73.3 date
Sat Jun 18 23:17:10 EEST 2016
root@2c86b132-1f04-467d-932f-14a732cfd61f:/# ssh root@172.29.73.3 date
^C
```

But ping is always successful between all peers (i.e. peer containers).

Also I tested from AWS Peer. Failed once only - to SydykPeer:
```
root@3306aa07-f315-498c-b6c8-bde6bcb8d24c:/# ssh root@172.29.73.3 date
^C
root@3306aa07-f315-498c-b6c8-bde6bcb8d24c:/# ssh root@172.29.73.3 date
Sat Jun 18 23:26:12 EEST 2016
root@3306aa07-f315-498c-b6c8-bde6bcb8d24c:/# ssh root@172.29.73.3 date
Sat Jun 18 23:26:20 EEST 2016
root@3306aa07-f315-498c-b6c8-bde6bcb8d24c:/# ssh root@172.29.73.3 date
Sat Jun 18 23:26:26 EEST 2016
```

[check-2-from-askat-peer.txt](https://github.com/subutai-io/p2p/files/321956/check-2-from-askat-peer.txt)
[check-2-from-aws-peer.txt](https://github.com/subutai-io/p2p/files/321955/check-2-from-aws-peer.txt)
[aws-peer-p2p-logs.txt](https://github.com/subutai-io/p2p/files/321954/aws-peer-p2p-logs.txt)

**Comment by crioto** [comment]
@asanaliev Nothing to do with p2p here. If you can ping containers - that means p2p connection was established and it works.

**Comment by akarasulu** [comment]
@soffokl @tzununbekov can you guys quickly take a look at this tomorrow morning?

**Comment by crioto** [comment]
Confirmed to be a p2p problem

**Comment by asanaliev** [comment]
Tested EZ-SSH on Mac OS. Looks the same issue: ping to p2p addresses works but some of SSH fails. 

I am using the same environment as above: 

![image](https://cloud.githubusercontent.com/assets/7465404/16177757/c194b484-3657-11e6-848b-2ecaac49d493.png)

Note: none of these peers is located on my laptop (Mac OS). AskatPeer is on a separate testing server which is connected (ethernet cable) to same WiFi router as my laptop.

To verify that I don't have Internet connection issues, I ping (see pane headers):
* form my laptop to hub.subut.ai
* from AskatPeer container to other containers in the env.

![image](https://cloud.githubusercontent.com/assets/7465404/16177799/a7018d4e-3658-11e6-8b28-761092f1a29c.png)

I restarted the p2p daemon and the Tray app. 

p2p logs: [macos-p2p-log.txt](https://github.com/subutai-io/p2p/files/322328/macos-p2p-log.txt)

p2p debug:
```
tulpar-2:~ askat$ /Applications/Subutai/p2p show
	06:72:cd:31:d5:66	10.57.64.245	swarm-18745392-996f-472d-9379-b453a53e7e69

tulpar-2:~ askat$ /Applications/Subutai/p2p debug
DEBUG INFO:
Number of gouroutines: 19
Instances information:
Hash: swarm-18745392-996f-472d-9379-b453a53e7e69
ID: 61dce239-3624-11e6-81c9-022d0fae0f03
Interface tap1, HW Addr: 06:72:cd:31:d5:66, IP: 10.57.64.245
Peers:
	--- fd7c6820-3622-11e6-8d32-022d0fae0f03 ---
		HWAddr: 06:de:45:eb:c9:f9
		IP: 10.57.64.1
		Endpoint: 192.168.0.190:42198
		Peer Address: 192.168.0.190:42198
		Proxy ID: 0
	--- End of fd7c6820-3622-11e6-8d32-022d0fae0f03 ---
	--- fdb4636e-3622-11e6-871f-022d0fae0f03 ---
		HWAddr: 06:05:bd:84:6d:3a
		IP: 10.57.64.3
		Endpoint: 54.93.222.10:54838
		Peer Address: 54.93.90.92:37078
		Proxy ID: 21
	--- End of fdb4636e-3622-11e6-871f-022d0fae0f03 ---
	--- fdbbf7de-3622-11e6-81bc-022d0fae0f03 ---
		HWAddr: 06:87:3f:9f:ae:31
		IP: 10.57.64.2
		Endpoint: 54.93.222.10:54838
		Peer Address: 158.181.250.17:45832
		Proxy ID: 4
	--- End of fdbbf7de-3622-11e6-81bc-022d0fae0f03 ---
```

p2p addresses to peers:
* 10.57.64.1: AskatPeer
* 10.57.64.2: SydykPeer
* 10.57.64.3: AWS

Pings from my laptop to all these peers are always successful: 

![image](https://cloud.githubusercontent.com/assets/7465404/16177850/f96a8ee0-3659-11e6-9959-b8e104cc60a6.png)

Checking port to AskatPeer is successful always (on same LAN via WiFi router):
```
tulpar-2:~ askat$ nc -v 10.57.64.1 10002
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif tap1
	src 10.57.64.245 port 59235
	dst 10.57.64.1 port 10002
	rank info not available
	TCP aux info available

Connection to 10.57.64.1 port 10002 [tcp/*] succeeded!
SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
```

Checking port to SydykPeer fails mostly (~80-90%):
```
tulpar-2:~ askat$ nc -v 10.57.64.2 10003
nc: connectx to 10.57.64.2 port 10003 (tcp) failed: Network is unreachable
tulpar-2:~ askat$ nc -v 10.57.64.2 10003
nc: connectx to 10.57.64.2 port 10003 (tcp) failed: Network is unreachable
tulpar-2:~ askat$ nc -v 10.57.64.2 10003
nc: connectx to 10.57.64.2 port 10003 (tcp) failed: Network is unreachable
```

Checking port to AwsPeer fails sometimes (~5%):
```
tulpar-2:~ askat$ nc -v 10.57.64.3 10004
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif tap1
	src 10.57.64.245 port 59264
	dst 10.57.64.3 port 10004
	rank info not available
	TCP aux info available

Connection to 10.57.64.3 port 10004 [tcp/*] succeeded!
SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
```

**Comment by crioto** [comment]
Latest fix allow to send large packets over p2p network:
```
ping 10.10.10.245 -s 65355 -c 4
PING 10.10.10.245 (10.10.10.245) 65355(65383) bytes of data.
65363 bytes from 10.10.10.245: icmp_seq=1 ttl=64 time=38.7 ms
65363 bytes from 10.10.10.245: icmp_seq=2 ttl=64 time=41.3 ms
65363 bytes from 10.10.10.245: icmp_seq=3 ttl=64 time=41.6 ms
65363 bytes from 10.10.10.245: icmp_seq=4 ttl=64 time=37.8 ms

--- 10.10.10.245 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3012ms
```

**Comment by asanaliev** [comment]
Created a new env using 3 peers:
![image](https://cloud.githubusercontent.com/assets/7465404/16236216/5ca4205c-37f9-11e6-8644-410a64171358.png)

All the peers have the latest update:
![image](https://cloud.githubusercontent.com/assets/7465404/16236252/7faa9194-37f9-11e6-98c1-7c88ff824f81.png)

===
Logged to the AskatPeer's container and testing connection to the containers (incl. itself). 

SSH to itself is always successful (10 of 10):
```
root@55639dc3-9cc9-48ca-baaf-de716c5bb3e9:/# ssh root@172.26.150.2 date
Tue Jun 21 18:48:04 EEST 2016
```
SSH to GooglePeer was successful 3 of 10: 
```
root@55639dc3-9cc9-48ca-baaf-de716c5bb3e9:/# ssh root@172.26.150.3 date
Tue Jun 21 18:48:49 EEST 2016
```
5 times got:
```
root@55639dc3-9cc9-48ca-baaf-de716c5bb3e9:/# ssh root@172.26.150.3 date
Connection closed by 172.26.150.3
```
Twice got:
```
root@55639dc3-9cc9-48ca-baaf-de716c5bb3e9:/# ssh root@172.26.150.3 date
Received disconnect from 172.26.150.3: 2: Packet corrupt
```
Small size ping  to GooglePeer is smooth:
```
root@55639dc3-9cc9-48ca-baaf-de716c5bb3e9:/# ping 172.26.150.3
PING 172.26.150.3 (172.26.150.3) 56(84) bytes of data.
64 bytes from 172.26.150.3: icmp_seq=1 ttl=64 time=140 ms
64 bytes from 172.26.150.3: icmp_seq=2 ttl=64 time=141 ms
64 bytes from 172.26.150.3: icmp_seq=3 ttl=64 time=139 ms
...
9 packets transmitted, 9 received, 0% packet loss, time 8011ms
```
But fails with bigger size:
```
root@55639dc3-9cc9-48ca-baaf-de716c5bb3e9:/# ping 172.26.150.3 -s 5000
PING 172.26.150.3 (172.26.150.3) 5000(5028) bytes of data.
^C
--- 172.26.150.3 ping statistics ---
26 packets transmitted, 0 received, 100% packet loss, time 25034ms
```

**Comment by crioto** [comment]
@asanaliev please check with latest version in dev

**Comment by asanaliev** [comment]
Beside the Mac specific problem, now it works. 

The Mac issue:
- connect from Mac (default terminal, iTerm) to RH
- attach to container
- run `ssh root@<remote-container-ip> date`

Although, at same time this works: `ssh root@<remote-container-ip>`
