### ISSUE TITLE
ping and ssh does not work

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/p2p#158]
I created x-peer and tried to ez-ssh to its containers but the shell hangs
![pasted image at 2016_06_23 07_24 pm](https://cloud.githubusercontent.com/assets/3367326/16312110/1eec264a-3995-11e6-9a19-fdb8decb33be.png)

Later it fails with `Connection timed out`

**Comment by crioto** [comment]
@Dilshat please check with latest version in dev

**Comment by Dilshat** [comment]
Fixed
