### ISSUE TITLE
`p2p show` and `ifconfig` shows different MACs for the same interface

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/p2p#159]
Sometimes (cannot say about conditions to reproduce, happens rarely on Dilshat's peers) `p2p show` command shows MAC addresses which differs from MAC in `ifconfig` output:

![pasted image at 2016_06_23 11_13 pm](https://cloud.githubusercontent.com/assets/13515865/16313062/5553416a-3999-11e6-8799-3669a2e72a85.png)

This situation causes partial cleanup malfunction - CLI uses those outputs to match environment VLAN and swarm id which should be removed

**Comment by crioto** [comment]
@tzununbekov please check with latest version in dev

**Comment by Dilshat** [comment]
still actual as @soffokl reported, p2p stop does not stop

**Comment by crioto** [comment]
@tzununbekov can you comment about this issue - does latest update fixed it?

**Comment by crioto** [comment]
Fixed

**Comment by tzununbekov** [comment]
Looks like fixed :D
