### ISSUE TITLE
Cannot ez-ssh to other peers containers

### ISSUE THREAD

**Issue by larenso** [subutai-io/p2p#163]
CANNOT ez-ssh to other peers containers, but CAN connect to owner pc container
tried the following configurations
larik is initiator (created environment)
larik--ok->larik
larik--fail->matabaev
larik--ok->abdysamat
larik--ok->zubaiduluu

here matabaev is initiator (created environment)
matabaev--ok->matabaev
matabaev--fail->larik
matabaev--fail->abdysamat
matabaev--fail->zubaiduluu

matabaev's rh p2p debug

Hash: swarm-64301a7b-3bd7-4646-a724-709d2ffc0386
ID: a248bc43-3e0b-11e6-8c15-022d0fae0f03
Interface p2p100, HW Addr: 06:30:67:43:e8:ab, IP: 10.154.153.2
Peers:
    --- f35c65d5-3e0b-11e6-8a86-022d0fae0f03 ---
        HWAddr: 06:8d:21:94:6c:75
        IP: 10.154.153.245
        Endpoint: 192.168.56.1:47719
        Peer Address: 192.168.56.1:47719
        Proxy ID: 0
    --- End of f35c65d5-3e0b-11e6-8a86-022d0fae0f03 ---

larik's rh p2p debug
Peers:
Hash: swarm-64301a7b-3bd7-4646-a724-709d2ffc0386
ID: ab5840d1-3e0b-11e6-8a50-022d0fae0f03
Interface p2p102, HW Addr: 06:69:75:ff:ba:fc, IP: 10.154.153.1
Peers:
    --- a0450daa-3e0b-11e6-8f07-022d0fae0f03 ---
        HWAddr: 06:64:67:28:64:b8
        IP: 10.154.153.3
        Endpoint: 54.93.164.238:36650
        Peer Address: 109.201.170.187:35221
        Proxy ID: 6
    --- End of a0450daa-3e0b-11e6-8f07-022d0fae0f03 ---

**Comment by crioto** [comment]
@larenso please check with the latest version

**Comment by crioto** [comment]
Fixed in 4.0.0
