### ISSUE TITLE
[Mac OS] SSH between remote containers fails 

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/p2p#164]
Related: #153 - _Ping works always, but SSH does not_.

As we got #153 fixed we found this issue which is specific to Mac OS only. This kind of commands fails `ssh root@<remote-container-ip> date` if a user logged from any Mac terminal (default terminal, iTerm).

For example:
1. SSH from Mac to any RH in env.
2. Attach to container (lxc-attach).
3. Run SSH command to another remote container: `ssh root@<remote-container-ip> date`.

As a result this command stays without any output. At same time, ping or `ssh root@<remote-container-ip>` work. Also, we couldn't reproduce this issue on Ubuntu or in other cases. These also work:
- SSH from Mac to Ubuntu OS, then check.
- SSH from Ubuntu OS to Mac, then check.

**Comment by crioto** [comment]
@asanaliev Can you please check if problem still persists?

**Comment by crioto** [comment]
Fixed in versions > 4.0.1
