### ISSUE TITLE
[Win 7] Fails to connect to container after some actions

### ISSUE THREAD

**Issue by larenso** [subutai-io/p2p#165]
Testcase:
1)create environment on hub, set ssh-key
2)connect to container (succeeded)
3)create environment via your subutai
4)connect to 2nd env container (succeeded)
5)connect to 1st env container (failed - cannot connect message)

![image](https://cloud.githubusercontent.com/assets/4501130/16574548/08a80974-42a2-11e6-9336-6cf8e63a4f26.png)

**Comment by crioto** [comment]
@larenso Can you provide output of 
```
p2p debug
p2p version
```
?

**Comment by larenso** [comment]
![image](https://cloud.githubusercontent.com/assets/4501130/16574632/d66510fa-42a2-11e6-925f-8053178c2f4e.png)

**Comment by crioto** [comment]
@larenso thank you. Also output of 
```ipconfig```
will be useful. I need to see list of TAP adapters created with their MAC addresses and assigned IPs

**Comment by larenso** [comment]
![image](https://cloud.githubusercontent.com/assets/4501130/16574651/ff8edf4c-42a2-11e6-82fa-520277510b7a.png)

**Comment by larenso** [comment]
@crioto yes, in progress, collecting

**Comment by larenso** [comment]
[ipcfg.txt](https://github.com/subutai-io/p2p/files/347120/ipcfg.txt)
[ipconfig.txt](https://github.com/subutai-io/p2p/files/347122/ipconfig.txt)

**Comment by larenso** [comment]
ipconfig.txt = ifconfig.txt (snappy)

**Comment by larenso** [comment]
pings
![image](https://cloud.githubusercontent.com/assets/4501130/16574869/478c2eec-42a5-11e6-865f-74a34148314e.png)

**Comment by crioto** [comment]
Thank you for detailed report @larenso I will update you after my investigation

**Comment by crioto** [comment]
@larenso please check with the latest version

**Comment by crioto** [comment]
Fixed in 4.0.0
