### ISSUE TITLE
Transferring files between containers is not stable

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/p2p#166]
**Testing environment**:
Peers: AWS, Google, 2x1 (two peers, one container each)
p2p version: 4.0.0-RC14-38-g5beb9e0

===
I tested file transfer using protocols HTTP and SCP. I used curl and nginx for HTTP: on Google peer I installed nginx and downloaded files via curl from AWS peer. 
Note: I ran continuously ping between containers to verify there were no generic network errors or other errors outside p2p connection. All tests I did when ping was stable. 

**HTTP**
1. Small file. Downloaded index.html (default from nginx), ~600 bytes. Only ~40% of tests completed successfully. In failed cases it takes either more than 30 sec (I terminated then), or connection error ("connection reset").
2. Big file. Tested with the VirtualBox installer (as an example), 61 MB. Failed in all cases: 10 of 10. Although, at same time I could successfully download the file from the official site: 10 of 10; in less than 20 sec each time. In other works, Internet connection of the container (outside p2p) was consistent.

Results are:
* Takes more than 3 min (and continues) without any output written to disk.
* Connection reset and downloading stops. Usually happens around 3 min. 

When testing with big file I notes the following:
1. Time for ping goes up. Usually ping is ~150 ms. But when downloading start the time goes up to 1500 or more. In 5-10 sec ping becomes normal. 
2. For some cases there was some output written to disk 4-8 KB, but not more (for file with size 61 MB).

**SCP**
1. Small file: same index.html. Downloaded using scp from Google peer to AWS peer. All failed: 10 of 10.
2. Big file. Didn't test b/c couldn't pass testing with small files.

**Comment by crioto** [comment]
@asanaliev can you confirm this is fixed? For messed up files we have #168

**Comment by asanaliev** [comment]
Tested with SCP. When coping files btw containers ping is stable.
