### ISSUE TITLE
[Win 8] Containers cannot ping and ssh each other

### ISSUE THREAD

**Issue by ezununbekov** [subutai-io/p2p#167]
Troubles start here - https://github.com/subutai-io/installers/issues/66
After tray is installed ez-ssh to both containers is successful, but these two cannot ping and ssh each other. Also tray periodically reports this error:
![5](https://cloud.githubusercontent.com/assets/16970241/16589953/55622588-42f7-11e6-8e3a-ea865ee7ecd6.JPG)
 
p2p show and p2p debug:
![4](https://cloud.githubusercontent.com/assets/16970241/16589990/79e7002c-42f7-11e6-9b38-82982eccc2d3.JPG)

**Comment by crioto** [comment]
@ezununbekov please check with the latest version

**Comment by crioto** [comment]
Fixed in latest versions
