### ISSUE TITLE
After "subutai update rh" existing p2p swarms are missing from "subutai management_network p2p -p"

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/p2p#170]
After "subutai update rh" existing p2p swarms are missing from "subutai management_network p2p -p" listing. But they appear after restarting p2p service.

**Comment by soffokl** [comment]
@Dilshat tested on latest subos, after update all environments active. 
If you will face this problem again, could you post `ifconfig` output, p2p logs and if possible provide access to your system.
