### ISSUE TITLE
Are these p2p errors are serious or warnings? 

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/p2p#184]
![screen shot 2016-07-25 at 5 50 10 pm](https://cloud.githubusercontent.com/assets/10051386/17119083/d2f699bc-5291-11e6-9f46-b42a8cd63a87.png)

[karaflogs2016-07-25 18-02-54.txt](https://github.com/subutai-io/p2p/files/382567/karaflogs2016-07-25.18-02-54.txt)

@crioto @Dilshat Is there a way I can through SS console get the logs for p2p on a RH or Peer like I do these karaf logs?

**Comment by crioto** [comment]
They are not. I will remove these messages in a next version
