### ISSUE TITLE
Peers doesn't reconnected after loosing connection to a proxy

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#192]

**Comment by akarasulu** [comment]
@crioto can you give brief status on this issue?

**Comment by crioto** [comment]
@akarasulu pretty hard to reproduce. In general reconnect works. Looks this was a single occurrence of this problem. Never catch it after this.

**Comment by akarasulu** [comment]
@soffokl said he encountered it so maybe he has way to reproduce this @crioto ?

**Comment by crioto** [comment]
@akarasulu we figured out this was not related. This was due to peers being offline

**Comment by akarasulu** [comment]
hmm ok then should we close this?

**Comment by crioto** [comment]
Closing this issue, but keeping in mind this might happen again.
