### ISSUE TITLE
[Win] P2P crashed 

### ISSUE THREAD

**Issue by btemir** [subutai-io/p2p#199]
What was done:
Installed Subutai on win8.1
Created environment with single container (master) 
Tried to ssh - Container is not ready
Stopped P2P service
Ran p2p daemon, waited when all interfaces created
Tried ssh to env from tray

Noted many messages "No IP address received"
Tried several times with the same
Next try: suddenly it started to connect, connected to local and remote containers
Tried to connect to local peer again
P2P crashed: 
![p2p_crash](https://cloud.githubusercontent.com/assets/16958983/18471440/b07adcc2-79d3-11e6-9660-91713b7e7d22.PNG)
restarted p2p daemon, tried to ssh:
![p2p_crash_1](https://cloud.githubusercontent.com/assets/16958983/18471507/154793a2-79d4-11e6-865e-9e5d902ea3e3.PNG)

**Comment by btemir** [comment]
I haven't noted before: all TAP interfaces have IPV4 address (Win8 was restarted)

![p2p_interfaces](https://cloud.githubusercontent.com/assets/16958983/18471670/dcd559d6-79d4-11e6-9089-4d339c6ec5ac.PNG)

**Comment by btemir** [comment]
On win 10 - some unsuccessfull connects to local cont, fail and crash after tried to connect to remote container
[p2p_log_win10.txt](https://github.com/subutai-io/p2p/files/469677/p2p_log_win10.txt)

**Comment by btemir** [comment]
p2p daemon starts very quickly, steps to reproduce on win10 (but need to check if it is reproducible on another machine or after restart):

1. stop Subutai Social P2P service
2. remove all TAP and ISATAP interfaces using DevManager
3. run p2p daemon (check if interfaces being created)
4. try to connect to local container
5. it fails (expectable as we have no interfaces)

[p2p_crash.txt](https://github.com/subutai-io/p2p/files/476390/p2p_crash.txt)

repeated several times, interfaces not created (need to find why)

**Comment by crioto** [comment]
Related to #223
