### ISSUE TITLE
ez-ssh doesn't work

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/p2p#200]
I installed the latest version of Subutai Social on Win 10. Created an environment using that peer only (one container only). Tried several times to ez-ssh (using Tray) to the container but without any success. 

Details you may see in the attached files:
[terminal-logs.txt](https://github.com/subutai-io/p2p/files/471744/terminal-logs.txt)
[p2p_log.txt](https://github.com/subutai-io/p2p/files/471741/p2p_log.txt)

RH P2P version: 4.0.2-10-gb8b6bb1. Packet version: 5.

P.S. Also getting problem with ez-ssh from Mac OS too. This may be some general problem related to p2p. After fixing for Windows I will check for Mac. Probably, the issue will be fixed there too.

**Comment by crioto** [comment]
@asanaliev We've updated p2p. Please update your installation and try again

**Comment by crioto** [comment]
Closing, since no response and similar reports for 7 days
