### ISSUE TITLE
Abnormal CPU consumption by p2p daemon

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/p2p#242]
Following issue first time appeared about a week ago and still exists for me:  
p2p daemon on all my peers constantly consumes 20-40% of CPU even without visible activity. Service logs seems to be ok. Abnormal CPU load starts with first environment creation and disappears if all environments are removed.         
![image](https://cloud.githubusercontent.com/assets/13515865/20253445/a82691d0-aa55-11e6-9872-b404eb9e2706.png)

I can provide an access to the peer with this issue if it is not reproducible on other hosts.

**Comment by crioto** [comment]
The problem was related to one goroutine which was not using proper timeouts and overall architecture of this function was wrong.

**Comment by akarasulu** [comment]
@tzununbekov Can you rerun your tests after confirming the proper version upgrade with p2p performance fixes from @crioto ?

**Comment by crioto** [comment]
As mentioned in subutai-io/subos#628 problem fixed.

**Comment by crioto** [comment]
After a deeper research of this problem it's made clear that problem is caused by multiple sleep functions in different goroutines. We will combine this routines into one to reduce sleep system calls.

**Comment by crioto** [comment]
Fixed
