### ISSUE TITLE
Documentation for p2p commands 

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/p2p#290]
Some thing exactly like this [here](https://github.com/subutai-io/subos/wiki/Attach) on the subos wiki for the agent's cli commands:

![selection_016-thumb](https://cloud.githubusercontent.com/assets/10051386/21964251/2d3f69d8-db51-11e6-84f0-7478db5e7084.png)

**Comment by crioto** [comment]
https://github.com/subutai-io/p2p/wiki/Cookbook
