### ISSUE TITLE
Create -nodaemon p2p Debian package 

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/p2p#341]
After finishing #340 just create this new package which skips setting up p2p daemon with systemd.

**Comment by akarasulu** [comment]
Let's see if the need pops up for it again. The problem I'm trying to avoid is human error where a user installs p2p on a system having the snap. Maybe this might morph into some code in the pre-install of the p2p package to check for the snap and p2p port availability.

**Comment by crioto** [comment]
This can be easily done on postinstall step - we check if snap service for p2p exists and if so we just don't create another one for p2p. We even can create this service unit, but not enable it, so if user uninstalls snap it can activate p2p systemd unit later

**Comment by ibragim13kz** [comment]
Not relevant.

**Comment by crioto** [comment]
This feature is no longer needed since we will provide a common Debian package both for peer and client side
