### ISSUE TITLE
info on how to run a DHT private server?

### ISSUE THREAD

**Issue by jaromil** [subutai-io/p2p#369]
Hi there, congrats for the good work here :^) I'm interested in testing subutai's p2p on a private network for now, is it possible to run my own DHT router? if yes, can this information be included in the documentation?
thanks for your time!

**Comment by crioto** [comment]
Hi @jaromil and thank you!

Unfortunately due to technical reason currently it is not possible to run private DHT router, but we have plans to make it public and easy to setup in the future. May I ask about the reasons you want to run private DHT? 

Thanks, Mike

**Comment by jaromil** [comment]
OK! thanks for the quick answer. One reason is to leave my own testing network completely private just in case nodes joining are vulnerable in some way, the second main reason is also that in case we start using subutai at dyne we'd like to run an open DHT server whose reliability is under our control. Hope this makes sense and keep up the good work!

**Comment by crioto** [comment]
Thank you @jaromil Yes, your points make sense. One note is that network is private when you connect and traffic is encrypted between nodes in one single swarm. Even if your host computer run multiple swarms, nodes from one swarm cannot communicate with nodes from other swarm. 
However, it is still possible some hosts can send unwanted/dangerous packets across their network and I'm not sure if public & open DHT routed will solve the problem in any way.

**Comment by jaromil** [comment]
Thanks, will study your code to understand better.
