### ISSUE TITLE
Cannot connect to containers from subutaiTray

### ISSUE THREAD

**Issue by SEFI2** [subutai-io/p2p#370]
When I am trying to connect to any container from tray->environment->some environment->container,
I am getting following error:
![image](https://user-images.githubusercontent.com/22672448/31211912-d1fb3074-a9be-11e7-85bf-5fca39098dab.png)

My p2p.exe daemon was started and it shows me these logs for this error:
![image](https://user-images.githubusercontent.com/22672448/31211979-37116bd6-a9bf-11e7-8ea4-753cc6795ad0.png)

**Comment by crioto** [comment]
Fixed
