### ISSUE TITLE
Fix handshake over proxy 

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#391]
When using proxy handshaking may fail for unknown reason. Most probably second party does not connect/get notified about proxy in time

**Comment by akarasulu** [comment]
@crioto This sounds really serious. Does it impact (especially slow or bandwidth starved) NAT'd peers specifically?

**Comment by crioto** [comment]
@akarasulu This is only on dev. After huge refactoring. And this impacts almost every peer behind NAT, no matter how fast/responsive it is.

**Comment by akarasulu** [comment]
Thanks @crioto for the heads up. Glad you marked this as HIGH priority.

**Comment by crioto** [comment]
Fixed
