### ISSUE TITLE
VM peer can't restore P2P connection after reboot

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/p2p#424]
I have environment which includes 1 AWS cloud peer, 2 local NATed VM peers, one of local peer was created a long ago from `core.ova` image, second local peer was created today from `ubuntu16.ova` image.
Tried to:
-  disconnect network on both local peers (by disconnecting network cards in VM settings)
- rebooted AWS cloud peer
- rebooted `core.ova` local peer
after all this actions p2p was restoring connections, ping between containers, EZSSH worked.

But when i rebooted `ubuntu16.ova` local peer, it returns error to `p2p debug` command:
```ubuntu@hpp2-mh:~$ subutai.p2p debug
[ERROR] 2017/11/01 14:19:46 Failed to connect to RPC dial tcp 127.0.0.1:52523: getsockopt: connection refused
```

here is the p2p logs before and after reboot on `ubuntu16.ova` local peer:
[p2p.log.zip](https://github.com/subutai-io/p2p/files/1434447/p2p.log.zip)

all peers has following versions:
```
ubuntu@hpp2-mh:~$ sudo subutai -v
sudo: unable to resolve host hpp2-mh
Subutai version 6.1.4
ubuntu@hpp2-mh:~$ 
ubuntu@hpp2-mh:~$ subutai.p2p version
p2p Cloud project 6.1.9. Packet version: 5
```

**Comment by crioto** [comment]
Fixed
