### ISSUE TITLE
P2P MSI should require a restart after installation

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/p2p#450]
I'm not certain why however several times after an installation p2p does not work and a reboot fixes things. I suspect the heavy changes to the OS drivers with the TAP network drivers are causing this issue. So a restart should be mandated on Windows when the MSI is installed. This is the only way to ensure correct operation. 

Now is this possible? I'm sure there is a way to mandate it. We just have to find it.

**Comment by crioto** [comment]
Not required anymore
