### ISSUE TITLE
CPU Utilization

### ISSUE THREAD

**Issue by lbthomsen** [subutai-io/p2p#462]
Subutai peer freshly installed and connected to hub (kl6).  One environment deployed with one tiny container.  On the server the p2p process is running at 100% CPU.

`oot@ncpws06:~# subutai.p2p status
swarm-f3b0454b-b92a-470b-9d17-636a21edc474 | 10.20.63.1
3a2d9eb0-d0ff-11e7-8b7d-06a75181366e|10.20.63.245|State:Connected|`

`DEBUG INFO:
Number of gouroutines: 13
Instances information:
Hash: swarm-f3b0454b-b92a-470b-9d17-636a21edc474
ID: a9212a87-d0fe-11e7-8d7c-06a75181366e
UDP Port: 55993
Interface p2p1, HW Addr: 06:e1:62:4c:7a:34, IP: 10.20.63.1
Peers:
        --- 3a2d9eb0-d0ff-11e7-8b7d-06a75181366e ---
                HWAddr: 06:14:e3:74:4d:57
                IP: 10.20.63.245
                Endpoint: 10.1.10.1:47508
                Peer Address: 10.1.10.1:47508
                Proxy ID: 0
        --- End of 3a2d9eb0-d0ff-11e7-8b7d-06a75181366e ---
`

**Comment by crioto** [comment]
I think this can be closed. Fix was confirmed
