### ISSUE TITLE
Cannot connect to p2p after upgrade

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/p2p#473]
### System Setup

* Mint Sonya 18 Desktop [up to date]
* `uname -a` : `Linux fermi 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
* Previous p2p and tray installed for dev

### Preparation

I first removed all p2p and tray packages from my Linux Mint 18.2 Desktop. I issued the following commands:

```bash
sudo apt-get remove subutai-tray
sudo apt-get remove subutai-p2p
```

Removal **seemed** to succeed with the package remove according apt-get. I proceeded to install the production Debian package of p2p from the website. I tried p2p debug and got this:

```console
akarasulu@fermi ~ $ p2p debug
[ERROR] 2017/12/02 05:53:56 Failed to connect to RPC dial tcp 127.0.0.1:52523: getsockopt: connection refused
```

After the apt-get remove, before installing the new package, I had noticed the old p2p process still running. I thought that the new package install might delete the lingering old process if the the apt-get remove did not do it so I had kept going: 

```console
akarasulu@fermi ~ $ ps -eaf | grep p2p
root       887     1  0 05:53 ?        00:00:00 /opt/subutai/bin/p2p daemon
akarasu+   945 23642  0 05:54 pts/1    00:00:00 grep --color=auto p2p
```

At this point, after the apt-get install, I realized the process was still the old one. So I removed the new package too then killed the process myself:

```console
akarasulu@fermi ~ $ sudo killall p2p
akarasulu@fermi ~ $ ps -eaf | grep p2p
akarasu+  1884 23642  0 06:04 pts/1    00:00:00 grep --color=auto p2p
```

Then I did an apt-get install again and tested to see if p2p debug was working and p2p debug was still not working even though a new process was running after the installation:

```console
akarasulu@fermi ~ $ ps -eaf | grep p2p
akarasu+  1884 23642  0 06:04 pts/1    00:00:00 grep --color=auto p2p
akarasulu@fermi ~ $ sudo apt install /home/akarasulu/Downloads/subutai-p2p.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'subutai-p2p' instead of '/home/akarasulu/Downloads/subutai-p2p.deb'
The following NEW packages will be installed:
  subutai-p2p
0 upgraded, 1 newly installed, 0 to remove and 34 not upgraded.
Need to get 0 B/2 508 kB of archives.
After this operation, 8 911 kB of additional disk space will be used.
Get:1 /home/akarasulu/Downloads/subutai-p2p.deb subutai-p2p amd64 6.2.5-0ubuntu1~trusty [2 508 kB]
Selecting previously unselected package subutai-p2p.
(Reading database ... 447779 files and directories currently installed.)
Preparing to unpack .../Downloads/subutai-p2p.deb ...
Unpacking subutai-p2p (6.2.5-0ubuntu1~trusty) ...
Setting up subutai-p2p (6.2.5-0ubuntu1~trusty) ...
akarasulu@fermi ~ $ p2p -v
p2p version 6.2.5
akarasulu@fermi ~ $ p2p debug
[ERROR] 2017/12/02 06:12:19 Failed to connect to RPC dial tcp 127.0.0.1:52523: getsockopt: connection refused
akarasulu@fermi ~ $ ps -eaf | grep p2p
root      3891     1  0 06:12 ?        00:00:00 /opt/subutai/bin/p2p daemon
akarasu+  4062 23642  0 06:12 pts/1    00:00:00 grep --color=auto p2p
```

**Comment by akarasulu** [comment]
OK it seems a reboot of the system fixed the problem. I have no idea why this was necessary. We need to fix this issue quickly. Although I have not tested other apt based systems like Ubuntu I suspect all will have this issue since it has to do with package scripts to install, start and stop the service with systemd.

**Comment by crioto** [comment]
Fixed
