### ISSUE TITLE
Old process still running after new installation

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/p2p#474]
### System
* macOS Sierra [up to date]
* uname -a: `Darwin newton 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64`

### Checks Before Installation

I had the dev p2p and tray on this machine before the installation:

```console
newton:tray akarasulu$ p2p -v
p2p version 6.3.0-dev
newton:tray akarasulu$ ps -eaf | grep p2p
    0  8575     1   0  3:03PM ??         0:56.32 /usr/local/bin/p2p daemon
    0 21002   441   0  6:30AM ??         0:00.01 /bin/bash /tmp/PKInstallSandbox.LeMmAi/Scripts/com.Subutai.P2P.ZNVk2j/postinstall /Users/akarasulu/Downloads/subutai-p2p.pkg /usr/local/share/subutai / /
  501 21018 19402   0  6:30AM ttys000    0:00.00 grep p2p
```

Unlike the tray I have no idea of how to uninstall p2p in macOS. Need a wiki page for this and filed and issue. Anyways just in case I also looked at the process in ActivityMonitor to see how long it has been running pid and all:

![screen shot 2017-12-02 at 6 33 49 am](https://user-images.githubusercontent.com/10051386/33509397-69ba050e-d72b-11e7-94ea-49b19499a0ec.png)

### After Installation

After the installation it seems the same process is still running with the same CPU time etc. Nothing changed. And what is odd is that it's still showing some dev region proxies it seems:

```console
newton:tray akarasulu$ p2p -v
p2p version 6.2.5
newton:tray akarasulu$ p2p debug
DEBUG INFO:
Number of gouroutines: 12
Instances information:
Hash: swarm-45fad9d9-d3b2-4119-b62f-415ceb7e1262
ID: c4c1c8e5-d6db-11e7-841b-06a75181366e
UDP Port: 55789
Interface tap1, HW Addr: 06:b4:32:52:be:34, IP: 10.59.135.245
Proxies:
	Proxy address: 52.77.219.59:40622
	Proxy address: 18.231.29.145:40622
	Proxy address: 13.56.234.71:40622
	Proxy address: 35.158.125.126:40622
Peers:

newton:tray akarasulu$ ps -eaf | grep p2p
    0  8575     1   0  3:03PM ??         0:56.48 /usr/local/bin/p2p daemon
  501 21088 19402   0  6:33AM ttys000    0:00.00 grep p2p
```

I killed the p2p daemon so it restarts. I **think**, it is the right instance running now, should be with the p2p -v showing the right 6.2.5 version. So I tried p2p debug again and now like Linux I am getting this connection issue:

```console
newton:tray akarasulu$ p2p debug
[ERROR] 2017/12/02 06:43:15 Failed to connect to RPC dial tcp [::1]:52523: getsockopt: connection refused
```

**Comment by akarasulu** [comment]
A reboot fixed it:

```console
newton:~ akarasulu$ p2p debug
DEBUG INFO:
Number of gouroutines: 7
Instances information:
```

**Comment by TerGunter** [comment]
fixed on master

**Comment by TerGunter** [comment]
fixed on prod
