### ISSUE TITLE
"p2p show -interfaces -all" returns removed interfaces 

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/p2p#475]
Console uses the command^ to clean up stale environments.
It relies on the data being actual.
We need to find workaround that fixes this bug without having to restart the p2p daemon,
since during cleanup of environments , nginx is restarted needlessly if p2p interface is already removed in the system when the command runs.

**Comment by crioto** [comment]
@Dilshat purpose of `-all` flag is to show all interfaces including those that not in use already. You can modify agent to not to add this flag and call only `p2p show --interfaces`.

**Comment by Dilshat** [comment]
Will be handled in https://github.com/subutai-io/agent/issues/242

**Comment by Dilshat** [comment]
Tried to add command `p2p stop --dev $p2p-interface` after `p2p stop -hash $swarm-hash` but it didnt help to remove interface from the output of `p2p show -interfaces -all`

**Comment by Dilshat** [comment]
Fixed from agent side
