### ISSUE TITLE
P2P service is not running on Win 10.

### ISSUE THREAD

**Issue by ibragim13kz** [subutai-io/p2p#477]
P2P service is not running on Win 10. 
![p2p service is not running](https://user-images.githubusercontent.com/33474101/33549681-8eddbe20-d915-11e7-8810-ba45ab89ec9f.png)

Also it tells about some errors with Windows Installer package . 
![p2p](https://user-images.githubusercontent.com/33474101/33549746-c6fe9e1e-d915-11e7-9bc5-21ba36739001.png)

**Comment by akarasulu** [comment]
This is a pretty serious issue. @crioto you going to have time to knock this out or you need some help?

**Comment by crioto** [comment]
@akarasulu I prepared new package for tests. Guys need to test it, because on my dev machine it was working. So I will ask our testers to try it today.

**Comment by crioto** [comment]
Fixed
