### ISSUE TITLE
Can't remove p2p from windows 10 using nssm.exe

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/p2p#483]
I can't remove old version of p2p. First i go to programs in settings and remove p2p from there, it shows removed. Then i check services menu in CP and see that p2p is running there. Then i use nssm tool to remove p2p, but when i click remove button on nssm, it shows - "can't remove service, perhaps it isn't installed". Then i re-check services and see that Subutai P2P is there and running. I reboot machine, start all over again and get the same result. The loop i can't get off...

**Comment by crioto** [comment]
nssm.exe dependency removed
