### ISSUE TITLE
Please commit mininet test framework

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/p2p#498]
@crioto I would like to start adding tests and feedback to the mininet test framework you worked on. Plus we need to think about how to get this into the devops process.

Please commit into the dev branch in a specific area (like say under `./mininet`). Please don't delay commit to get things organized. That's not important to me. Just dump as is and I want to get ideas quickly on how I can move forward.

**Comment by ibragim13kz** [comment]
Not relevant.

**Comment by crioto** [comment]
We have switched to our own integration test scripts which involve real environments created from blueprints
