### ISSUE TITLE
Avoid using proxy servers between peers on the same LAN

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/p2p#499]
Two peers on the same LAN should not have to use proxy servers to communicate. 

Simple Case: Two Peers on Same Network
----------------------------------------------------------

In the simplest basis case, two peers on the same subnet should connect directly. I think this case is covered however we need a mininet integration test to make sure we do not regress. Perhaps in the test the hops between peers should be tested through a traceroute or something. Perhaps this can also be combined with some timing metric where pings should not be more than 10ms or so to make sure traffic is not going out to a proxy and back.

Nested Case: Two Peers on w/ Natting
---------------------------------------------------

This case I know for sure does not work and requires a proxy making round trips extremely long. I had two peers on the same LAN but on different networks. The nested network was natted by a router into the top network of the LAN. For example, 172.16.1.0/24 had a router attached with a NAT'd 192.168.1.0/24 subnet inside. One peer was 172.16.1.106 and another ways 192.168.1.20. The same proxy situation occurs when using p2p+tray on a client inside the nested subnet. The latency is huge.

Many cases get more complex with private networks of hypervisors. We should be able to handle these situations without having to use a proxy.

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by AlinaPenkina** [comment]
Done
