### ISSUE TITLE
SSH buttons appear and disappear on production Debian

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/p2p#548]
I have environment on prod Debian 9 with 4 peers and 15 containers. After env-t was created, some ssh buttons became active, then inactive, then others became active and others - inactive.
Logs are attached.

[-.txt.zip](https://github.com/subutai-io/p2p/files/1642222/-.txt.zip)

**Comment by crioto** [comment]
@amol4anoff reproduce in master please

**Comment by crioto** [comment]
@amol4anoff any updates?

**Comment by amol4anoff** [comment]
@crioto will now do

**Comment by amol4anoff** [comment]
@crioto Tray has some installation error. If prod ver is removed, master cannot be installed.

**Comment by amol4anoff** [comment]
@crioto ok, its good on master on debian. Warmup is short.

**Comment by crioto** [comment]
Closing
