### ISSUE TITLE
P2P production is not installed after i removed master version

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/p2p#577]
I had p2p master on mac, then removed it and then installed p2p prod version, i noticed that ssh button is inactive, made p2p debug and noticed that i still have p2p master:

OptDyn:~ admin$ p2p debug
Version: 6.2.9-master Build: 6.2.9-43-g7b73c96
Number of gouroutines: 750
Instances information:

OptDyn:~ admin$

**Comment by crioto** [comment]
Restart it manually

**Comment by amol4anoff** [comment]
Now installed.

**Comment by crioto** [comment]
@amol4anoff please recheck status of this issue

**Comment by TerGunter** [comment]
fixed on master

**Comment by AlinaPenkina** [comment]
Done.
