### ISSUE TITLE
Logs are not rotating on MacOS

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/p2p#596]
P2P logs on MacOS are not rotating, everytime it's required to execute command to re-fresh them - sudo rm -f /var/log/p2p.log

**Comment by amol4anoff** [comment]
Seems it's the same. Yesterday (03.04.18) i tried to get and send logs, executing "cat /var/log/p2p.log" but noticed that log file contains 30 000+ lines of logs. Seems it's not refreshing automatically on MacOS yet.

**Comment by TerGunter** [comment]
fixed on master

**Comment by TerGunter** [comment]
ашчув щт зкщв
