### ISSUE TITLE
Improve warmup time

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#668]
In order to improve warmup time we need to refactor p2p in the following way:
- [x] **Receive proxies prior to establishing any connection.** 
_Proxy retrieval/handshaking process will take not more than 3 second. After this period whether p2p received or not any proxies - the daemon will request other peers_
- [x] **Make a new state that will combine all connectivity tasks.** 
_It will UDP hole punch all known endpoints for 1 minute. After this period passes target peer will switch to one of two states:_

- _Connection was established at least with one endpoint -> Start Routing procedure_
- _Connection was not established -> Disconnect this peer_

- [x] **Routing.** 
_New routing method must be executed each time we have changes in a list of connected endpoints. Routing method will sort endpoints array in the following way: LAN endpoints -> Internet endpoints -> Proxy endpoints._ 

- [x] **Endpoint watcher.** 
_Method that will try to establish connection with other, not connected endpoints, but not in aggressive mode like we do during connection period. Also this method watch if some endpoints have been disconnected. Each time this method notices any changes it will call Routing method_.

**Comment by AlinaPenkina** [comment]
Fixed.
