### ISSUE TITLE
P2P weight error

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/p2p#673]
* What's your Operating System?  - it's MacOS

* Describe your problem and steps to reproduce it - I downloaded p2p package for MacOS, then started an installation, then noticed that p2p is going to take just 36 KB of space on HDD.

* Show output of `p2p debug`
OptDyn:~ admin$ p2p debug
Version: 6.2.17 Build: 6.2.17
Uptime: 1 h 36 m 13 s
Number of gouroutines: 68
Instances information:
Bootstrap nodes:
	35.177.107.208:6881
Hash: swarm-4ff7960d-f87e-4a00-ab0e-babbe796ca1f
ID: 1b80ff8c-0b26-11e8-80a4-06a75181366e
UDP Port: 55789
Interface tap1, HW Addr: 06:92:bc:31:de:fd, IP: 10.48.26.245
Proxies:
	Proxy address: 52.67.8.214:40622 Assigned Endpoint: 52.67.8.214:20006
	Proxy address: 18.195.241.137:40622 Assigned Endpoint: 18.195.241.137:20004
	Proxy address: 13.57.177.230:40622 Assigned Endpoint: 13.57.177.230:20008
	Proxy address: 13.250.10.232:40622 Assigned Endpoint: 13.250.10.232:20003
Peers:
	--- 471e2f49-0b26-11e8-83a5-06a75181366e ---
		HWAddr: 06:18:dd:96:ce:4b
		IP: 10.48.26.4
		Endpoint: 18.231.170.5:39983
		Peer Address: 18.231.170.5:39983
		Using proxy: No
	--- End of 471e2f49-0b26-11e8-83a5-06a75181366e ---
	--- a8303b0a-0b30-11e8-89b1-06a75181366e ---
		HWAddr: 06:97:2c:70:4b:14
		IP: 10.48.26.246
		Endpoint: 172.16.0.227:46183
		Peer Address: 172.16.0.227:46183
		Using proxy: No
	--- End of a8303b0a-0b30-11e8-89b1-06a75181366e ---
	--- 135e3ac6-0b26-11e8-83e8-06a75181366e ---
		HWAddr: 06:2a:6f:bd:4a:00
		IP: 10.48.26.1
		Endpoint: 18.231.187.177:48402
		Peer Address: 18.231.187.177:48402
		Using proxy: No
	--- End of 135e3ac6-0b26-11e8-83e8-06a75181366e ---
Bootstrap nodes:
	35.177.107.208:6881
Hash: swarm-74882dd0-a80b-477f-be84-cd267a218c96
ID: 1b82a84b-0b26-11e8-89b8-06a75181366e
UDP Port: 52194
Interface tap0, HW Addr: 06:fc:52:05:c0:46, IP: 10.233.134.245
Proxies:
	Proxy address: 13.57.177.230:40622 Assigned Endpoint: 13.57.177.230:20013
	Proxy address: 13.250.10.232:40622 Assigned Endpoint: 13.250.10.232:20007
	Proxy address: 52.67.8.214:40622 Assigned Endpoint: 52.67.8.214:20015
	Proxy address: 18.195.241.137:40622 Assigned Endpoint: 18.195.241.137:20007
Peers:
	--- a8321d71-0b30-11e8-8b0c-06a75181366e ---
		HWAddr: 06:39:8b:a5:3b:be
		IP: 10.233.134.246
		Endpoint: 172.16.0.227:55562
		Peer Address: 172.16.0.227:55562
		Using proxy: No
	--- End of a8321d71-0b30-11e8-8b0c-06a75181366e ---
	--- 12fafad9-0b26-11e8-88f1-06a75181366e ---
		HWAddr: 06:65:21:70:27:1d
		IP: 10.233.134.1
		Endpoint: 18.231.187.177:45766
		Peer Address: 18.231.187.177:45766
		Using proxy: No
	--- End of 12fafad9-0b26-11e8-88f1-06a75181366e ---
Bootstrap nodes:
	35.177.107.208:6881
Hash: swarm-54969555-ddb1-482d-a42f-479115e2ad77
ID: 51274a87-0b26-11e8-8091-06a75181366e
UDP Port: 58681
Interface tap2, HW Addr: 06:d0:b0:d5:4c:ed, IP: 10.230.201.245
Proxies:
	Proxy address: 18.195.241.137:40622 Assigned Endpoint: 18.195.241.137:20036
	Proxy address: 13.57.177.230:40622 Assigned Endpoint: 13.57.177.230:20036
	Proxy address: 13.250.10.232:40622 Assigned Endpoint: 13.250.10.232:20031
	Proxy address: 52.67.8.214:40622 Assigned Endpoint: 52.67.8.214:20034
Peers:
	--- 48f98ba7-0b26-11e8-8992-06a75181366e ---
		HWAddr: 06:6a:7c:98:8e:fc
		IP: 10.230.201.2
		Endpoint: 10.48.26.4:32873
		Peer Address: 10.48.26.4:32873
		Using proxy: No
	--- End of 48f98ba7-0b26-11e8-8992-06a75181366e ---
	--- a8303c75-0b30-11e8-8352-06a75181366e ---
		HWAddr: 06:c1:82:3f:64:52
		IP: 10.230.201.246
		Endpoint: 172.16.0.227:46708
		Peer Address: 172.16.0.227:46708
		Using proxy: No
	--- End of a8303c75-0b30-11e8-8352-06a75181366e ---
Bootstrap nodes:
	35.177.107.208:6881
Hash: swarm-9ce7beca-4cb0-4d34-b4c4-d9273d1b5579
ID: e045247a-0b26-11e8-844a-06a75181366e
UDP Port: 57742
Interface tap3, HW Addr: 06:7f:fb:64:44:0c, IP: 10.174.78.245
Proxies:
	No proxies in use
Peers:
	--- 75898208-0b26-11e8-8621-06a75181366e ---
		HWAddr: 06:84:3d:fc:4a:e1
		IP: 10.174.78.2
		Endpoint: 18.231.159.215:48839
		Peer Address: 18.231.159.215:48839
		Using proxy: No
	--- End of 75898208-0b26-11e8-8621-06a75181366e ---
	--- 74695cd5-0b26-11e8-874c-06a75181366e ---
		HWAddr: 06:5d:b3:96:52:f8
		IP: 10.174.78.1
		Endpoint: 10.48.26.1:52217
		Peer Address: 10.48.26.1:52217
		Using proxy: No
	--- End of 74695cd5-0b26-11e8-874c-06a75181366e ---
	--- a830e0e9-0b30-11e8-87a9-06a75181366e ---
		HWAddr: 06:c2:e1:8c:6f:34
		IP: 10.174.78.246
		Endpoint: 172.16.0.227:50863
		Peer Address: 172.16.0.227:50863
		Using proxy: No
	--- End of a830e0e9-0b30-11e8-87a9-06a75181366e ---
Bootstrap nodes:
	35.177.107.208:6881
Hash: swarm-ec79c253-cdde-46cf-8155-5ee484895e67
ID: ec662b45-0b27-11e8-8784-06a75181366e
UDP Port: 56063
Interface tap4, HW Addr: 06:a5:f4:cb:81:26, IP: 10.83.34.245
Proxies:
	Proxy address: 18.195.241.137:40622 Assigned Endpoint: 18.195.241.137:20070
	Proxy address: 13.57.177.230:40622 Assigned Endpoint: 13.57.177.230:20071
	Proxy address: 13.250.10.232:40622 Assigned Endpoint: 13.250.10.232:20069
	Proxy address: 52.67.8.214:40622 Assigned Endpoint: 52.67.8.214:20070
Peers:
	--- 728cdb7c-0b27-11e8-85dd-06a75181366e ---
		HWAddr: 06:14:a4:2b:dc:92
		IP: 10.83.34.1
		Endpoint: 10.174.78.1:49448
		Peer Address: 10.174.78.1:49448
		Using proxy: No
	--- End of 728cdb7c-0b27-11e8-85dd-06a75181366e ---
	--- 73bb608a-0b27-11e8-8bad-06a75181366e ---
		HWAddr: 06:00:79:cc:a2:07
		IP: 10.83.34.2
		Endpoint: 18.231.159.215:44942
		Peer Address: 18.231.159.215:44942
		Using proxy: No
	--- End of 73bb608a-0b27-11e8-8bad-06a75181366e ---
	--- a8322261-0b30-11e8-8b33-06a75181366e ---
		HWAddr: 06:ae:4d:53:4c:cf
		IP: 10.83.34.246
		Endpoint: 172.16.0.227:60760
		Peer Address: 172.16.0.227:60760
		Using proxy: No
	--- End of a8322261-0b30-11e8-8b33-06a75181366e ---
	--- 72865494-0b27-11e8-8b91-06a75181366e ---
		HWAddr: 06:03:55:a1:6e:7f
		IP: 10.83.34.3
		Endpoint: 18.231.170.5:42068
		Peer Address: 18.231.170.5:42068
		Using proxy: No
	--- End of 72865494-0b27-11e8-8b91-06a75181366e ---
Bootstrap nodes:
	35.177.107.208:6881
Hash: swarm-73b8fda8-3b01-48c1-a5fe-2bddbc821072
ID: aeba8968-0b2a-11e8-8c31-06a75181366e
UDP Port: 61971
Interface tap5, HW Addr: 06:a4:e7:c0:03:e8, IP: 10.213.70.245
Proxies:
	Proxy address: 13.57.177.230:40622 Assigned Endpoint: 13.57.177.230:20066
	Proxy address: 13.250.10.232:40622 Assigned Endpoint: 13.250.10.232:20075
	Proxy address: 52.67.8.214:40622 Assigned Endpoint: 52.67.8.214:20064
	Proxy address: 18.195.241.137:40622 Assigned Endpoint: 18.195.241.137:20075
Peers:
	--- 6c9d6388-0b2a-11e8-8a18-06a75181366e ---
		HWAddr: 06:20:38:a7:9e:ca
		IP: 10.213.70.1
		Endpoint: 18.231.159.215:50153
		Peer Address: 18.231.159.215:50153
		Using proxy: No
	--- End of 6c9d6388-0b2a-11e8-8a18-06a75181366e ---
	--- a830e5f8-0b30-11e8-8331-06a75181366e ---
		HWAddr: 06:75:16:73:96:a3
		IP: 10.213.70.246
		Endpoint: 172.16.0.227:46023
		Peer Address: 172.16.0.227:46023
		Using proxy: No
	--- End of a830e5f8-0b30-11e8-8331-06a75181366e ---
Bootstrap nodes:
	35.177.107.208:6881
Hash: swarm-9abf9bf5-1b19-4739-ae51-4b5beedd95d6
ID: 7fbede6c-0b2c-11e8-870e-06a75181366e
UDP Port: 55623
Interface tap6, HW Addr: 06:58:c0:50:e7:b8, IP: 10.70.31.245
Proxies:
	Proxy address: 13.57.177.230:40622 Assigned Endpoint: 13.57.177.230:20092
	Proxy address: 13.250.10.232:40622 Assigned Endpoint: 13.250.10.232:20091
	Proxy address: 52.67.8.214:40622 Assigned Endpoint: 52.67.8.214:20087
	Proxy address: 18.195.241.137:40622 Assigned Endpoint: 18.195.241.137:20088
Peers:
	--- 508bb6ba-0b2c-11e8-803f-06a75181366e ---
		HWAddr: 06:51:32:7c:a3:88
		IP: 10.70.31.1
		Endpoint: 85.93.88.163:45265
		Peer Address: 85.93.88.163:45265
		Using proxy: No
	--- End of 508bb6ba-0b2c-11e8-803f-06a75181366e ---
	--- a8303bf2-0b30-11e8-86c4-06a75181366e ---
		HWAddr: 06:96:f1:b9:8c:05
		IP: 10.70.31.246
		Endpoint: 172.16.0.227:50219
		Peer Address: 172.16.0.227:50219
		Using proxy: No
	--- End of a8303bf2-0b30-11e8-86c4-06a75181366e ---
Bootstrap nodes:
	35.177.107.208:6881
Hash: swarm-88758779-0c38-4707-b1ca-da6c924bc173
ID: d915c460-0b2c-11e8-82f0-06a75181366e
UDP Port: 51584
Interface tap7, HW Addr: 06:5f:cf:7c:83:9e, IP: 10.175.203.245
Proxies:
	Proxy address: 13.57.177.230:40622 Assigned Endpoint: 13.57.177.230:20088
	Proxy address: 13.250.10.232:40622 Assigned Endpoint: 13.250.10.232:20087
	Proxy address: 52.67.8.214:40622 Assigned Endpoint: 52.67.8.214:20088
	Proxy address: 18.195.241.137:40622 Assigned Endpoint: 18.195.241.137:20087
Peers:
	--- a4dd1aff-0b2c-11e8-898d-06a75181366e ---
		HWAddr: 06:d1:aa:99:a9:60
		IP: 10.175.203.1
		Endpoint: 13.57.177.230:20081
		Peer Address: 77.95.56.186:56053
		Using proxy: Yes
	--- End of a4dd1aff-0b2c-11e8-898d-06a75181366e ---
	--- a4ddb158-0b2c-11e8-8acd-06a75181366e ---
		HWAddr: 06:1c:89:d7:57:91
		IP: 10.175.203.2
		Endpoint: 13.250.10.232:20085
		Peer Address: 77.95.56.186:48583
		Using proxy: Yes
	--- End of a4ddb158-0b2c-11e8-8acd-06a75181366e ---
	--- a82fd6d3-0b30-11e8-8b2d-06a75181366e ---
		HWAddr: 06:a3:52:fd:2e:6c
		IP: 10.175.203.246
		Endpoint: 172.16.0.227:55123
		Peer Address: 172.16.0.227:55123
		Using proxy: No
	--- End of a82fd6d3-0b30-11e8-8b2d-06a75181366e ---

OptDyn:~ admin$ 

* Attach p2p log or sensible part of it - [P2PlogsMac.zip](https://github.com/subutai-io/p2p/files/1698882/P2PlogsMac.zip)

<img width="665" alt="light" src="https://user-images.githubusercontent.com/33647491/35858428-970034d8-0b66-11e8-93a6-ca0d6e7bd90d.png">

**Comment by TerGunter** [comment]
fixed on prod
