### ISSUE TITLE
Failed to set MAC

### ISSUE THREAD

**Issue by chennqqi** [subutai-io/p2p#702]
* What's your Operating System? 

Centos 6 and Centos7

* Describe your problem and steps to reproduce it

./p2p daemon
./p2p start --hash xxxxxx -ip 192.168.11.11
when i try to start join..

* Show output of `p2p debug`

Version: 6.2.18 Build: 6.2.18
Uptime: 0 h 5 m 11 s
Number of gouroutines: 10
Instances information:

* Attach p2p log or sensible part of it

[INFO] 2018/02/25 18:49:59 vptp1 TAP Device created
[INFO] 2018/02/25 18:49:59 Configuring vptp1. IP: 192.168.50.245, Mac: 06:22:f7:3a:1f:9e
[INFO] 2018/02/25 18:49:59 Setting 192.168.50.245 IP on device vptp1
[INFO] 2018/02/25 18:49:59 Setting 06:22:f7:3a:1f:9e MAC on device vptp1
[ERROR] 2018/02/25 18:49:59 Failed to set MAC: exit status 2
[ERROR] 2018/02/25 18:49:59 Failed to configure interface: exit status 2

**Comment by chennqqi** [comment]
i think should call `ifconfig dev down` before setMac()

**Comment by crioto** [comment]
Hi @chennqqi 
Never tested it on centos and I'm sure it is not necessary to bring interface down on debian (mint and ubuntu) and arch linux. I will try to reproduce and fix it on centos. 

Thank you.

**Comment by AlinaPenkina** [comment]
Done.
