### ISSUE TITLE
windows not work, and create a lot of tap device

### ISSUE THREAD

**Issue by chennqqi** [subutai-io/p2p#705]
* What's your Operating System? 

windows7 64bit

* Describe your problem and steps to reproduce it

p2p daemon
p2p start ...

* Show output of `p2p debug`

Version: 6.2.18 Build: 6.2.18
Uptime: 0 h 4 m 2 s
Number of gouroutines: 18
Instances information:
Bootstrap nodes:
        35.177.107.208:6881

* Attach p2p log or sensible part of it
[ERROR] 2018/02/25 22:57:03 Failed to retrieve Mac
[INFO] 2018/02/25 22:54:00 Network configuration tool found: C:\Windows\system32\netsh.exe
[INFO] 2018/02/25 22:54:00 Acquired control over TAP interface: 本地连接 9
[INFO] 2018/02/25 22:54:01 Acquired control over TAP interface: 本地连接 7
[INFO] 2018/02/25 22:54:02 Acquired control over TAP interface: 本地连接 12
[INFO] 2018/02/25 22:54:04 Acquired control over TAP interface: 本地连接 10
[INFO] 2018/02/25 22:54:05 Acquired control over TAP interface: 本地连接 8
[INFO] 2018/02/25 22:54:07 Acquired control over TAP interface: 本地连接 11
[INFO] 2018/02/25 22:54:09 Acquired control over TAP interface: 本地连接 2
[INFO] 2018/02/25 22:54:10 Acquired control over TAP interface: 本地连接 6
[INFO] 2018/02/25 22:54:11 Acquired control over TAP interface: 本地连接 5

[ERROR] 2018/02/25 22:54:27 Failed to close TAP interface: %!s(<nil>)

**Comment by crioto** [comment]
Hey @chennqqi 
Yes, Windows creates a lot (10) interfaces in advance, because this is how TAP driver behaves - we can't create new interfaces on demand, so we pre-allocate them.

**Comment by chennqqi** [comment]
I see, the problem is all these TAP interfaces are link down.
`p2p status` show connected, but network is unusable。

**Comment by chennqqi** [comment]
I test windows 2003, it worked well.
I confused why the tap nic repeated link up and link down.

**Comment by crioto** [comment]
Yes, this is how it supposed to work (I'm still looking for a better solution). First TAP interfaces are all down, and they link up during interface configuration

**Comment by chennqqi** [comment]
I'v test an other window7 in different network environment.
All anti-virus software were closed.
It seems that confiugre win7 tap device is complicated.

**Comment by crioto** [comment]
That's interesting. I never tried to do this on Win 7 myself, but I know people using Win 7 and they have reported that TAP interface configuration went without any problems. 
Can you post output of `ipconfig` from Win7?

**Comment by chennqqi** [comment]
Windows IP 配置


以太网适配器 本地连接 12:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 本地连接 11:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 本地连接 10:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 本地连接 9:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 本地连接 8:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 本地连接 7:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 本地连接 6:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 本地连接 5:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 本地连接 4:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 本地连接 2:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

无线局域网适配器 无线网络连接 3:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

以太网适配器 本地连接:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

无线局域网适配器 无线网络连接:

   连接特定的 DNS 后缀 . . . . . . . : 
   本地链接 IPv6 地址. . . . . . . . : fe80::49d:9f56:c4f3:dad%12
   IPv4 地址 . . . . . . . . . . . . : 192.168.2.7
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.2.1

以太网适配器 VirtualBox Host-Only Network:

   连接特定的 DNS 后缀 . . . . . . . : 
   本地链接 IPv6 地址. . . . . . . . : fe80::2c32:7376:ad89:f3be%14
   IPv4 地址 . . . . . . . . . . . . : 192.168.56.1
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 

隧道适配器 Reusable ISATAP Interface {E37A4DE8-EC13-485E-A147-3D7E599AB535}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{E9A17F9D-77D8-4CC0-B089-EBF162B6E6B7}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 本地连接* 11:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 本地连接* 12:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 本地连接* 13:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 本地连接* 14:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 本地连接* 17:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{CA7C402B-6CC3-462C-943D-2775E6CF0A37}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{061A5F8E-193B-483A-9804-37213D1C1C4F}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{20BC57A3-7041-4B1D-9758-FF3EE89F5252}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 Teredo Tunneling Pseudo-Interface:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 Reusable ISATAP Interface {9D91D98D-1FF7-4412-BAC8-E4728F186420}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{F19F0D00-DF86-449D-A19F-023A789574F1}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 本地连接* 18:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{6C01E4E5-B9AA-4823-87EA-52DE6A117DAB}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{1365F164-4A6A-4A41-8B20-CACE133C0501}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{5E750B0F-D5BA-4CA6-9490-7CCE77E90427}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{C11D9391-5111-4FA7-A00B-0F89DE76BCAD}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{DEAE0C36-53CF-4BF7-82D2-E8909185CE4D}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{9C55ADF7-B9D1-45A7-9C9B-1F29316BEFB4}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{02A8ECF1-BC6E-4AFC-8889-5C4CCAB0D522}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{ACDF7F90-A129-4F69-95F3-A22F373AC3C7}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . : 

隧道适配器 isatap.{68EB8EDF-CC78-4AD7-960A-1B2495CAB20C}:

   媒体状态  . . . . . . . . . . . . : 媒体已断开
   连接特定的 DNS 后缀 . . . . . . . :

**Comment by chennqqi** [comment]
translate to english.

Windows IP configuration


Ethernet Adapter Local Connection 12:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Ethernet Adapter Local Connection 11:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Ethernet Adapter Local Connection 10:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Ethernet adapter local connection 9:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Ethernet adapter local connection 8:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Ethernet Adapter Local Connection 7:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Ethernet adapter local connection 6:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Ethernet adapter local connection 5:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Ethernet adapter local connection 4:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Ethernet Adapter Local Connection 2:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Wireless LAN Adapter Wi-Fi Internet connection 3:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Ethernet adapter local connection:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Wireless LAN Adapter Wireless LAN:

   Connect to a specific DNS suffix......:
   Local Link IPv6 Address......: Fe80 :: 49d: 9f56: c4f3: dad% 12
   IPv4 Address......... .: 192.168.2.7
   Subnet Mask.........: 255.255.255.0
   Default Gateway..........: 192.168.2.1

Ethernet Adapter VirtualBox Host-Only Network:

   Connect to a specific DNS suffix......:
   Local Link IPv6 Address......: Fe80 :: 2c32: 7376: ad89: f3be% 14
   IPv4 address.........: 192.168.56.1
   Subnet Mask.........: 255.255.255.0
   Default gateway............:

Tunnel Adapter Reusable ISATAP Interface {E37A4DE8-EC13-485E-A147-3D7E599AB535}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {E9A17F9D-77D8-4CC0-B089-EBF162B6E6B7}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter Local Connection * 11:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter Local Connection * 12:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter Local Connection * 13:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter Local Connection * 14:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter Local Connection * 17:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {CA7C402B-6CC3-462C-943D-2775E6CF0A37}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {061A5F8E-193B-483A-9804-37213D1C1C4F}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {20BC57A3-7041-4B1D-9758-FF3EE89F5252}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter Teredo Tunneling Pseudo-Interface:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter Reusable ISATAP Interface {9D91D98D-1FF7-4412-BAC8-E4728F186420}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {F19F0D00-DF86-449D-A19F-023A789574F1}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter Local Connection * 18:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {6C01E4E5-B9AA-4823-87EA-52DE6A117DAB}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {1365F164-4A6A-4A41-8B20-CACE133C0501}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {5E750B0F-D5BA-4CA6-9490-7CCE77E90427}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {C11D9391-5111-4FA7-A00B-0F89DE76BCAD}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {DEAE0C36-53CF-4BF7-82D2-E8909185CE4D}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {9C55ADF7-B9D1-45A7-9C9B-1F29316BEFB4}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {02A8ECF1-BC6E-4AFC-8889-5C4CCAB0D522}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {ACDF7F90-A129-4F69-95F3-A22F373AC3C7}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

Tunnel Adapter isatap. {68EB8EDF-CC78-4AD7-960A-1B2495CAB20C}:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:

**Comment by chennqqi** [comment]
Windows IP configuration

   Host name ...........: xxxx
   Primary DNS suffix.........:
   Node type ... ... ... ...:
   IP routing enabled.......: No
   WINS Proxy Enabled .........: No

Ethernet Adapter Local Connection 12:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:
   Description ...........: TAP-Windows Adapter V9 # 10
   Physical Address ... ... ... ...:: 00-FF-F1-9F-0D-00
   DHCP enabled........: No
   Automatic configuration enabled........: Yes

Ethernet Adapter Local Connection 11:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:
   Description......... .: TAP-Windows Adapter V9 # 9
   Physical Address ......... .: 00-FF-6C-01-E4-E5
   DHCP enabled........: No
   Automatic configuration enabled........: Yes

Ethernet Adapter Local Connection 10:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:
   Description .......... .: TAP-Windows Adapter V9 # 8
   Physical Address......... .: 00-FF-13-65-F1-64
   DHCP enabled........: No
   Automatic configuration enabled........: Yes

Ethernet adapter local connection 9:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:
   Description......... .: TAP-Windows Adapter V9 # 7
   Physical Address ... ... ... ...:: 00-FF-5E-75-0B-0F
   DHCP enabled........: No
   Automatic configuration enabled........: Yes

Ethernet adapter local connection 8:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:
   Description......... .: TAP-Windows Adapter V9 # 6
   Physical Address ........... .: 00-FF-C1-1D-93-91
   DHCP enabled........: No
   Automatic configuration enabled........: Yes

Ethernet Adapter Local Connection 7:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:
   Description .......... .: TAP-Windows Adapter V9 # 5
   Physical Address ... ... ... ...:: 00-FF-9C-55-AD-F7
   DHCP enabled........: No
   Automatic configuration enabled........: Yes

Ethernet adapter local connection 6:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:
   Description .......... .: TAP-Windows Adapter V9 # 4
   Physical Address ... ... ... ...:.: 00-FF-02-A8-EC-F1
   DHCP enabled........: No
   Automatic configuration enabled........: Yes

Ethernet adapter local connection 5:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:
   Description......... .: TAP-Windows Adapter V9 # 3
   Physical Address ... ... ... ...:: 00-FF-AC-DF-7F-90
   DHCP enabled........: No
   Automatic configuration enabled........: Yes

Ethernet adapter local connection 4:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:
   Description .......... .: TAP-Windows Adapter V9 # 2
   Physical Address ... ... ... ... .: 00-FF-DE-AE-0C-36
   DHCP enabled........: No
   Automatic configuration enabled........: Yes

Ethernet Adapter Local Connection 2:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:
   Description .......... .: TAP-Windows Adapter V9
   Physical Address ...... ... ... .: 00-FF-68-EB-8E-DF
   DHCP enabled........: No
   Automatic configuration enabled........: Yes

Wireless LAN Adapter Wi-Fi Internet connection 3:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:
   Description ........... .: Microsoft Virtual WiFi Miniport Adapter
   Physical Address ...... ... ... .: 22-B9-A5-21-B4-CD
   DHCP enabled........: Yes
   Automatic configuration enabled........: Yes

Ethernet adapter local connection:

   Media Status ..........: Media disconnected
   Connect to a specific DNS suffix......:
   Description......... .: Qualcomm Atheros AR8151 PCI-E Gigabit Ethernet Controller (NDIS 6.20)
   Physical Address ......... .: F4-6D-04-8A-3A-C7
   DHCP enabled........: Yes
   Automatic configuration enabled........: Yes

Wireless LAN Adapter Wireless LAN:

   Connect to a specific DNS suffix......:
   Description.......... .: Qualcomm Atheros AR9285 Wireless Network Adapter
   Physical Address ......... .: E0-B9-A5-21-B4-CD
   DHCP enabled........: Yes
   Automatic configuration enabled........: Yes
   Local link IPv6 address..... .: fe80 :: 49d: 9f56: c4f3: dad% 12 (preferred)
   IPv4 address........ .: 192.168.2.7 (preferred)
   Subnet Mask.........: 255.255.255.0
   Lease time......: February 22, 2018 23:22:18
   Lease time expired.....: February 28, 2018 9:26:10
   Default Gateway..........: 192.168.2.1
   DHCP Server, ..., ...:: 192.168.2.1
   DHCPv6 IAID........ .: 216054181
   DHCPv6 Client DUID ... ... ... .: 00-01-00-01-1E-E5-AE-EC-E0-B9-A5-21-B4-CD
   DNS Server....... .: 123.125.81.6
                                       192.168.2.1
   NetBIOS on TCPIP.....: Enabled

Ethernet Adapter VirtualBox Host-Only Network:

   Connect to a specific DNS suffix......:
   Description ............: VirtualBox Host-Only Ethernet Adapter
   Physical Address..........: 0A-00-27-00-00-0E
   DHCP enabled........: No
   Automatic configuration enabled........: Yes
   Local link IPv6 address......: Fe80 :: 2c32: 7376: ad89: f3be% 14 (preferred)
   IPv4 address........ .: 192.168.56.1 (preferred)
   Subnet Mask.........: 255.255.255.0
   Default gateway............:

**Comment by crioto** [comment]
Alright, thanks. 
Yes, more looks like p2p failed to configure interfaces. I'll try to reproduce it and see what's wrong exactly.
Thank you

**Comment by chennqqi** [comment]
Will the virtual machine cause this problem?

**Comment by crioto** [comment]
You mean you were running Win7 inside a VM?

**Comment by chennqqi** [comment]
no,no, i install vm in win7. vm also install some virtual nics. i use p2p directly in win7

**Comment by crioto** [comment]
Actually some people have reported similar problem when they was running a VM on their machines on Windows 10.

**Comment by AlinaPenkina** [comment]
Tap creation works well on Windows: tap interface should down in the beginning and link up during interface configuration.
The problem might be related with VM.
