### ISSUE TITLE
P2P doesn't works with old environments.

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/p2p#756]
On Windows and Linux based systems it happened.
When new p2p is deployed to master, all my environment didn't work (Status on all old envs. was: "failed"). Then I deleted all old environments and started to create others, p2p with new environments connecting successfully.
[p2p.txt](https://github.com/subutai-io/p2p/files/1824850/p2p.txt)

**Comment by amol4anoff** [comment]
Same in ubuntu. If an environment is older than one day state is - failed.

**Comment by amol4anoff** [comment]
@crioto

**Comment by crioto** [comment]
Thanks. I'm working on these issues.

**Comment by ibragim13kz** [comment]
Fixed in Master.

**Comment by ibragim13kz** [comment]
Fixed.
