### ISSUE TITLE
Improper uninstallation of p2p requires to delete registry key

### ISSUE THREAD

**Issue by Erkin97** [subutai-io/p2p#766]
Windows OS
Command ``sc delete "Subutai p2p`` didn't help
Registry key needed to remove manually:``HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Subutai P2P``
![image](https://user-images.githubusercontent.com/22586805/37862792-3596c398-2f7d-11e8-9408-e79d31dc923b.png)

**Comment by azretkenzhaliev** [comment]
The root of this problem is issue #774

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by AlinaPenkina** [comment]
Done.
