### ISSUE TITLE
p2p did not establish connection after MasterBazaar deployment.

### ISSUE THREAD

**Issue by Shahrizada** [subutai-io/p2p#771]
Mac [master]
"Ready" state of envs became "connecting" while MasterBazaar was deploying and did not return. 
debug:
Last login: Wed Mar 28 15:13:08 on ttys002
-bash: nexport: command not found
Shahris-Air:~ shahrizadakarasulu$ p2p debug
Version: 6.3.0-master Build: 6.2.20-165-gd48c26f
Uptime: 4 h 3 m 41 s
Number of gouroutines: 29
Bootstrap nodes information:
  52.58.220.11:6881 Rx: 10652822 Tx: 1096895
Instances information:
Bootstrap nodes:
Hash: swarm-8492bcad-6d79-412e-b0cb-d81c18063166
ID: ad30b181-3267-11e8-8676-060555473160
UDP Port: 61099
Network interfaces: 192.168.77.111 
P2P Interface , HW Addr: 06:cc:01:ca:aa:a6, IP: 127.0.0.1
Proxies: No proxies in use
Peers:
Bootstrap nodes:
Hash: swarm-92c0d732-7137-4550-a48e-1bb193dbd3ae
ID: ae4ce6d2-3267-11e8-87e5-060555473160
UDP Port: 59796
Network interfaces: 192.168.77.111 
P2P Interface , HW Addr: 06:1b:4f:1d:bc:12, IP: 127.0.0.1
Proxies: No proxies in use
Peers:
Bootstrap nodes:
Hash: swarm-5c330b11-ae57-4da9-aa3b-436177037e9d
ID: ae805f91-3267-11e8-810f-060555473160
UDP Port: 50412
Network interfaces: 192.168.77.111 
P2P Interface , HW Addr: 06:16:38:9a:cc:fe, IP: 127.0.0.1
Proxies: No proxies in use
Peers:
Bootstrap nodes:
Hash: swarm-4c0757ea-7322-4e4d-8b44-2f7ae3840df2
ID: b3fa6e28-3267-11e8-85fa-060555473160
UDP Port: 50228
Network interfaces: 192.168.77.111 
P2P Interface , HW Addr: 06:dd:48:aa:4b:88, IP: 127.0.0.1
Proxies: No proxies in use
Peers:
Bootstrap nodes:
Hash: swarm-27b93369-fa9b-4332-93d9-1efd00328f76
ID: b53b1bb7-3267-11e8-82dc-060555473160
UDP Port: 65359
Network interfaces: 192.168.77.111 
P2P Interface , HW Addr: 06:11:5b:3d:cb:4a, IP: 127.0.0.1
Proxies: No proxies in use
Peers:

Shahris-Air:~ shahrizadakarasulu$

**Comment by Shahrizada** [comment]
I have 7 healthy envs. Mostly on cloud peers. 
p2p debug after restarting client:

Last login: Wed Mar 28 15:13:36 on ttys003
-bash: nexport: command not found
Shahris-Air:~ shahrizadakarasulu$ p2p debug
Version: 6.3.0-master Build: 6.2.20-165-gd48c26f
Uptime: 0 h 2 m 23 s
Number of gouroutines: 56
Bootstrap nodes information:
  52.58.220.11:6881 Rx: 243025 Tx: 41977
Instances information:
Bootstrap nodes:
Hash: swarm-5c330b11-ae57-4da9-aa3b-436177037e9d
ID: bc9c59d8-326b-11e8-892f-060555473160
UDP Port: 62550
Network interfaces: 192.168.77.111 
P2P Interface tap0, HW Addr: 06:86:06:ba:2a:73, IP: 10.138.52.246
Proxies: 35.159.10.202:40622/20033 54.233.167.241:40622/20029 13.250.117.166:40622/20032 52.58.220.11:40622/20033 54.183.200.212:40622/20037 
Peers:
	--- 9f1e35bf-3267-11e8-8a36-060555473160 ---
	States: Waiting for connection | Unknown
	No IP assigned
	Endpoints pool: 192.168.233.1:38362 192.168.56.1:38362 172.28.128.1:38362 96.246.161.207:38362 54.183.200.212:20006 
	--- End of 9f1e35bf-3267-11e8-8a36-060555473160 ---
Bootstrap nodes:
Hash: swarm-4c0757ea-7322-4e4d-8b44-2f7ae3840df2
ID: c6c59389-326b-11e8-8dbc-060555473160
UDP Port: 57513
Network interfaces: 192.168.77.111 
P2P Interface tap1, HW Addr: 06:ac:50:ed:cd:5b, IP: 10.122.89.246
Proxies: 54.183.200.212:40622/20040 35.159.10.202:40622/20036 54.233.167.241:40622/20032 13.250.117.166:40622/20034 52.58.220.11:40622/20036 
Peers:
	--- 0665b3f3-326c-11e8-8c6a-060555473160 ---
	States: Initializing connection | Initializing connection
	No IP assigned
	Endpoints pool: 10.154.0.2:41789 10.10.10.254:41789 172.23.79.252:41789 172.28.215.252:41789 172.26.91.252:41789 172.31.238.249:41789 172.20.88.251:41789 172.21.120.252:41789 172.21.247.251:41789 35.197.222.55:41789 54.233.167.241:20020 13.250.117.166:20017 52.58.220.11:20023 54.183.200.212:20022 35.159.10.202:20023 
	--- End of 0665b3f3-326c-11e8-8c6a-060555473160 ---
	--- 9f0ef95c-3267-11e8-8132-060555473160 ---
	States: Connected | Connected
	Network: 10.122.89.245 06:b0:43:8e:b7:e3
	Endpoint: 96.246.161.207:42006
	All Endpoints: 96.246.161.207:42006 54.183.200.212:20005 
	Endpoints pool: 192.168.233.1:42006 192.168.56.1:42006 172.28.128.1:42006 96.246.161.207:42006 54.183.200.212:20005 
	--- End of 9f0ef95c-3267-11e8-8132-060555473160 ---

Shahris-Air:~ shahrizadakarasulu$

**Comment by ibragim13kz** [comment]
Issue moved to [subutai-io/control-center #783](https://github.com/subutai-io/control-center/issues/783) via [**ZenHub**](https://www.zenhub.com/)
