### ISSUE TITLE
Implement configuration

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#793]
We need to have a configuration object, which stores configurable parameters of p2p. Right now we are using YAML files to store configuration, however it is used only to configure one option - `iptool`, which is `ifconfig` on MacOS, `ip` on Linux and `netsh` on Windows. 
To extend p2p functionality in the future we need to make it more configurable. This is why we need a separate configuration object that reads provided configuration and stores it's parameters in memory for fast access by other objects.

**Comment by AlinaPenkina** [comment]
Fixed.
