### ISSUE TITLE
Status Ready but I can't connect by ssh, it shows connection refused.

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/p2p#794]
OS-Ubuntu
I have READY environment state, but when I open terminal, it shows me that connection refused

Version: 6.3.0-master Build: 6.2.20-196-g3ae2294
Uptime: 22 h 25 m 13 s
Number of gouroutines: 54
Bootstrap nodes information:
  52.58.220.11:6881 Rx: 185049100 Tx: 70924632
Instances information:
Bootstrap nodes:
Hash: swarm-eae09a82-0627-4c4f-8ede-9aaee509b0a3
ID: 00c5413c-3a3e-11e8-8d2a-060555473160
UDP Port: 45337
Network interfaces: 172.16.0.248 192.168.122.1 172.28.128.1 
P2P Interface vptp3, HW Addr: 06:dc:29:db:ce:18, IP: 10.131.223.245
Proxies: 54.183.200.212:40622/20029 35.159.10.202:40622/20030 54.233.167.241:40622/20030 13.250.117.166:40622/20027 52.58.220.11:40622/20030 
Peers:
    --- 017025e9-3a44-11e8-8b2c-060555473160 ---
    States: Connected | Connected
    Network: 10.131.223.246 00:ff:af:c3:ea:ca
    Endpoint: 172.16.0.234:63759
    All Endpoints: 172.16.0.234:63759 52.58.220.11:20050 35.159.10.202:20050 13.250.117.166:20047 54.183.200.212:20046 54.233.167.241:20049 
    Endpoints pool: 172.16.0.234:63759 192.168.56.1:63759 172.7.4.100:63759 172.8.4.100:63759 172.9.4.100:63759 77.95.61.194:63759 52.58.220.11:20050 35.159.10.202:20050 13.250.117.166:20047 54.183.200.212:20046 54.233.167.241:20049 
    --- End of 017025e9-3a44-11e8-8b2c-060555473160 ---
    --- a52d89ea-3a3d-11e8-8505-060555473160 ---
    States: Connected | Connected
    Network: 10.131.223.2 06:94:45:1a:24:b4
    Endpoint: 192.168.88.208:50562
    All Endpoints: 192.168.88.208:50562 52.58.220.11:20026 35.159.10.202:20026 13.250.117.166:20022 54.183.200.212:20022 54.233.167.241:20025 
    Endpoints pool: 192.168.121.56:50562 192.168.88.208:50562 10.10.10.254:50562 77.95.61.194:50562 52.58.220.11:20026 35.159.10.202:20026 13.250.117.166:20022 54.183.200.212:20022 54.233.167.241:20025 
    --- End of a52d89ea-3a3d-11e8-8505-060555473160 ---
    --- a8cee5fb-3a3d-11e8-80cc-060555473160 ---
    States: Connected | Connected
    Network: 10.131.223.1 06:32:fa:8d:e5:a9
    Endpoint: 192.168.88.201:36308
    All Endpoints: 192.168.88.201:36308 52.58.220.11:20028 35.159.10.202:20028 54.183.200.212:20025 13.250.117.166:20025 54.233.167.241:20027 
    Endpoints pool: 192.168.121.39:36308 192.168.88.201:36308 10.10.10.254:36308 172.23.83.253:36308 77.95.61.194:36308 52.58.220.11:20028 35.159.10.202:20028 54.183.200.212:20025 13.250.117.166:20025 54.233.167.241:20027 
    --- End of a8cee5fb-3a3d-11e8-80cc-060555473160 ---
Bootstrap nodes:
Hash: swarm-82282c7c-883c-4d2f-9b0c-e96de63dcaf6
ID: a4f9ac29-3a3f-11e8-8407-060555473160
UDP Port: 60293
Network interfaces: 172.16.0.248 192.168.122.1 172.28.128.1 10.131.223.245 
P2P Interface vptp4, HW Addr: 06:0f:7e:18:fd:ea, IP: 10.88.203.245
Proxies: 54.183.200.212:40622/20031 35.159.10.202:40622/20038 54.233.167.241:40622/20038 13.250.117.166:40622/20035 52.58.220.11:40622/20038 
Peers:
    --- fc6726a2-3a3d-11e8-8442-060555473160 ---
    States: Connected | Connected
    Network: 10.88.203.1 06:9f:17:66:1b:b3
    Endpoint: 192.168.88.204:47895
    All Endpoints: 192.168.88.204:47895 52.58.220.11:20029 35.159.10.202:20029 54.183.200.212:20027 13.250.117.166:20026 54.233.167.241:20029 
    Endpoints pool: 192.168.121.164:47895 192.168.88.204:47895 10.10.10.254:47895 77.95.61.194:47895 52.58.220.11:20029 35.159.10.202:20029 54.183.200.212:20027 13.250.117.166:20026 54.233.167.241:20029 
    --- End of fc6726a2-3a3d-11e8-8442-060555473160 ---
    --- ef05a7e5-3a43-11e8-858a-060555473160 ---
    States: Connected | Connected
    Network: 10.88.203.246 00:ff:1c:38:e6:f5
    Endpoint: 172.16.0.234:50124
    All Endpoints: 172.16.0.234:50124 52.58.220.11:20019 35.159.10.202:20019 13.250.117.166:20017 54.183.200.212:20018 54.233.167.241:20019 
    Endpoints pool: 172.16.0.234:50124 192.168.56.1:50124 172.0.4.100:50124 172.4.4.100:50124 172.1.4.100:50124 172.2.4.100:50124 172.7.4.100:50124 172.3.4.100:50124 172.8.4.100:50124 172.9.4.100:50124 172.5.4.100:50124 172.6.4.100:50124 77.95.61.194:50124 52.58.220.11:20019 35.159.10.202:20019 13.250.117.166:20017 54.183.200.212:20018 54.233.167.241:20019 
    --- End of ef05a7e5-3a43-11e8-858a-060555473160 ---
Bootstrap nodes:
Hash: swarm-071a2626-91fe-4d9c-a9b0-9fca0f77e6cb
ID: 6d0bc7ad-39e2-11e8-838d-060555473160
UDP Port: 44708
Network interfaces: 172.16.0.248 192.168.122.1 172.28.128.1 10.131.223.245 10.88.203.245 
P2P Interface vptp0, HW Addr: 06:80:d6:4a:b9:b5, IP: 127.0.0.1
Proxies: 52.58.220.11:40622/20007 54.183.200.212:40622/20007 35.159.10.202:40622/20007 54.233.167.241:40622/20007 13.250.117.166:40622/20007 
Peers:
Bootstrap nodes:
Hash: swarm-a6c73679-f8e9-4efe-b105-3137c13ab1dd
ID: 127c3400-3a18-11e8-8e35-060555473160
UDP Port: 35088
Network interfaces: 172.16.0.248 192.168.122.1 172.28.128.1 10.131.223.245 10.88.203.245 
P2P Interface vptp2, HW Addr: 06:a3:b8:d4:75:28, IP: 127.0.0.1
Proxies: 35.159.10.202:40622/20011 54.233.167.241:40622/20011 13.250.117.166:40622/20011 52.58.220.11:40622/20011 54.183.200.212:40622/20011 
Peers:
    --- 6ee33b0d-3a4a-11e8-87ad-060555473160 ---
    States: Waiting for connection | Unknown
    No IP assigned
    Endpoints pool: 172.16.0.234:49644 192.168.56.1:49644 77.95.61.194:49644 
    --- End of 6ee33b0d-3a4a-11e8-87ad-060555473160 ---
    --- 78225300-3a4a-11e8-8c31-060555473160 ---
    States: Waiting for connection | Unknown
    No IP assigned
    Endpoints pool: 172.16.0.234:49650 192.168.56.1:49650 77.95.61.194:49650 
    --- End of 78225300-3a4a-11e8-8c31-060555473160 ---
    --- 776d323e-3a47-11e8-8145-060555473160 ---
    States: Connected | Connected
    Network: 10.146.124.1 06:59:66:87:69:db
    Endpoint: 35.159.10.202:20015
    All Endpoints: 35.159.10.202:20015 54.183.200.212:20015 52.58.220.11:20015 54.233.167.241:20015 13.250.117.166:20024 
    Endpoints pool: 10.0.2.15:53631 192.168.1.211:53631 172.28.128.3:53631 10.10.10.254:53631 172.27.131.251:53631 172.18.84.251:53631 172.22.35.252:53631 172.19.73.252:53631 172.16.119.251:53631 96.246.161.207:53631 54.183.200.212:20015 35.159.10.202:20015 54.233.167.241:20015 52.58.220.11:20015 13.250.117.166:20024 
    --- End of 776d323e-3a47-11e8-8145-060555473160 ---
    --- 93dd0dda-3a4a-11e8-89ae-060555473160 ---
    States: Waiting for connection | Unknown
    No IP assigned
    Endpoints pool: 172.16.0.234:60113 192.168.56.1:60113 77.95.61.194:60113 
    --- End of 93dd0dda-3a4a-11e8-89ae-060555473160 ---
Bootstrap nodes:
Hash: swarm-725bdc7f-2c61-41be-9027-4669d8ffd98b
ID: 971170cf-3a1a-11e8-85a6-060555473160
UDP Port: 44913
Network interfaces: 172.16.0.248 192.168.122.1 172.28.128.1 10.131.223.245 10.88.203.245 
P2P Interface vptp1, HW Addr: 06:70:f2:8b:2f:3f, IP: 127.0.0.1
Proxies: 35.159.10.202:40622/20012 54.233.167.241:40622/20012 13.250.117.166:40622/20012 52.58.220.11:40622/20012 54.183.200.212:40622/20012 
Peers:
    --- 815aee39-3a4a-11e8-8362-060555473160 ---
    States: Waiting for connection | Unknown
    No IP assigned
    Endpoints pool: 172.16.0.234:49665 192.168.56.1:49665 77.95.61.194:49665 
    --- End of 815aee39-3a4a-11e8-8362-060555473160 ---
    --- 6ef30828-3a4a-11e8-816f-060555473160 ---
    States: Waiting for connection | Unknown
    No IP assigned
    Endpoints pool: 172.16.0.234:49643 192.168.56.1:49643 77.95.61.194:49643 
    --- End of 6ef30828-3a4a-11e8-816f-060555473160 ---
    --- 771c6485-3a47-11e8-89cd-060555473160 ---
    States: Connected | Connected
    Network: 10.110.74.1 06:47:06:e8:8b:85
    Endpoint: 96.246.161.207:44313
    All Endpoints: 96.246.161.207:44313 52.58.220.11:20014 54.183.200.212:20014 35.159.10.202:20014 54.233.167.241:20014 13.250.117.166:20023 
    Endpoints pool: 10.0.2.15:44313 192.168.1.211:44313 172.28.128.3:44313 10.10.10.254:44313 172.27.131.251:44313 172.18.84.251:44313 172.22.35.252:44313 172.19.73.252:44313 172.16.119.251:44313 96.246.161.207:44313 54.183.200.212:20014 52.58.220.11:20014 35.159.10.202:20014 54.233.167.241:20014 13.250.117.166:20023 
    --- End of 771c6485-3a47-11e8-89cd-060555473160 ---
    --- 8afa601a-3a4a-11e8-866d-060555473160 ---
    States: Waiting for connection | Unknown
    No IP assigned
    Endpoints pool: 172.16.0.234:49672 192.168.56.1:49672 77.95.61.194:49672 
    --- End of 8afa601a-3a4a-11e8-866d-060555473160 ---

**Comment by AlinaPenkina** [comment]
[myp2p (1).log](https://github.com/subutai-io/p2p/files/1886258/myp2p.1.log)

**Comment by crioto** [comment]
Should happen rare. Also note that this might be an agent issue as well. You can determine it by sending ping to RH

**Comment by AlinaPenkina** [comment]
Fixed on master

**Comment by AlinaPenkina** [comment]
I still face this problem. I created issue for Erkin, to provide valid information about p2p state in control center.
