### ISSUE TITLE
Missing p2p environments on peer.

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/p2p#799]
p2p can't see some environments on peer side.

**Comment by crioto** [comment]
This is because of p2p.save file on peers. p2p wasn't able to read it - it seems it was broken during save. We need to make it in more plain text format (currently it uses gob).

**Comment by crioto** [comment]
How to reproduce: 

- Create environment with multiple peers.
- SSH to peers and start restarting p2p multiple times

There is a chance you will catch it: your environment will no longer appear in `p2p show` or `p2p debug` output

**Comment by crioto** [comment]
Improve tests for Encode and Decode methods. Currently you cover only one situation - when every setting was provided:
```
        P2Pinstance.Args.IP = "10.10.10.1"
	P2Pinstance.Args.Mac = "Mac"
	P2Pinstance.Args.Dev = "Dev"
	P2Pinstance.Args.Hash = "Hash"
	P2Pinstance.Args.Dht = "Dht"
	P2Pinstance.Args.Keyfile = "Keyfile"
	P2Pinstance.Args.Key = "Key"
	P2Pinstance.Args.TTL = "TTL"
	P2Pinstance.Args.Fwd = true
	P2Pinstance.Args.Port = 0
```
What you need to do is to exclude different configuration lines and check in test how it behaves. For example:
```
        P2Pinstance.Args.IP = "10.10.10.1"
	P2Pinstance.Args.Mac = "Mac"
	P2Pinstance.Args.Dht = "Dht"
	P2Pinstance.Args.Keyfile = "Keyfile"
	P2Pinstance.Args.Key = "Key"
	P2Pinstance.Args.TTL = "TTL"
	P2Pinstance.Args.Fwd = true
	P2Pinstance.Args.Port = 0
```
In the example above we are missing two arguments. Make your tests more generic and cover all possible cases

**Comment by crioto** [comment]
@AlinaPenkina could you please try to reproduce it on master? 
We are trying to understand how wide this problem is. What you need to do:

- SSH into peer
- Run `p2p show` and count number of P2P instances
- restart p2p services
- Run `p2p show` again after 1 minute and count P2P instances
- Compare numbers and report results please

P.S. This needs to be done on 3+ different peers.

**Comment by AlinaPenkina** [comment]
@azretkenzhaliev @crioto 
Peer qavms-kg3_mast-DB: before:  3 envs, after restart: 2 envs.
Peer qavms-kg5_mast-F1: before:  4 envs, after restart:  4 envs.
Peer qavms-kg1_mast-E4: before: 2 envs, after restart: 1env.
Peer OptDyn Inc's Cloud peer-F4: before:  5 envs(but on bazaar it shows 7envs), after restart: 5 envs

**Comment by AlinaPenkina** [comment]
I still face this after restart p2p.service on peer.

**Comment by AlinaPenkina** [comment]
root@subutai:~# subutai-master.p2p debug
Version: 6.3.1 Build: 6.3.1-210-g75baf33
Uptime: 3 h 31 m 7 s
Number of gouroutines: 41
Bootstrap nodes information:
  52.58.220.11:6881 Rx: 4606005 Tx: 213553
Instances information:
Bootstrap nodes:
Hash: swarm-3ac920d7-c127-4f5a-8052-915469b22617
ID: 8048a851-478a-11e8-8b6c-060555473160
UDP Port: 53021
Network interfaces: 192.168.121.54 192.168.88.248 172.21.107.251 172.21.107.252 172.18.19.252 172.24.124.252 172.20.84.252 172.20.84.251 10.10.10.254 
P2P Interface p2p1, HW Addr: 06:0b:39:0b:93:7d, IP: 10.231.109.1
Proxies: 52.58.220.11:40622/20001 54.183.200.212:40622/20001 35.159.10.202:40622/20001 54.233.167.241:40622/20001 13.250.117.166:40622/20001 
Peers:
    --- c0da446c-47a3-11e8-88d2-060555473160 ---
    States: CONNECTED | CONNECTED
    Network: 10.231.109.246 06:15:59:bd:ae:1a
    Endpoint: 18.232.35.52:59071
    All Endpoints: 18.232.35.52:59071 52.58.220.11:20052 35.159.10.202:20051 54.183.200.212:20064 54.233.167.241:20064 13.250.117.166:20065 
    Endpoints pool: 172.31.81.43:59071 10.10.10.254:59071 172.18.114.252:59071 18.232.35.52:59071 52.58.220.11:20052 54.183.200.212:20064 35.159.10.202:20051 54.233.167.241:20064 13.250.117.166:20065 
    --- End of c0da446c-47a3-11e8-88d2-060555473160 ---
Bootstrap nodes:
Hash: swarm-cd2c3df9-ab6c-4881-9082-c40d78d7d576
ID: 806c3a71-478a-11e8-8efc-060555473160
UDP Port: 53402
Network interfaces: 192.168.121.54 192.168.88.248 172.21.107.251 172.21.107.252 172.18.19.252 172.24.124.252 172.20.84.252 172.20.84.251 10.10.10.254 10.231.109.1 
P2P Interface p2p3, HW Addr: 06:77:11:04:a6:47, IP: 10.241.183.1
Proxies: 54.233.167.241:40622/20026 13.250.117.166:40622/20025 52.58.220.11:40622/20039 54.183.200.212:40622/20026 35.159.10.202:40622/20039 
Peers:
    --- 1c8dea71-4784-11e8-8347-060555473160 ---
    States: CONNECTED | CONNECTED
    Network: 10.241.183.250 00:ff:01:43:ca:0e
    Endpoint: 192.168.66.64:63136
    All Endpoints: 192.168.66.64:63136 35.159.10.202:20050 52.58.220.11:20050 54.233.167.241:20050 13.250.117.166:20057 
    Endpoints pool: 192.168.56.1:63136 172.8.4.100:63136 172.7.4.100:63136 172.6.4.100:63136 172.5.4.100:63136 10.117.84.246:63136 172.9.4.100:63136 192.168.66.64:63136 5.57.15.122:63136 54.183.200.212:20049 35.159.10.202:20050 54.233.167.241:20050 13.250.117.166:20057 52.58.220.11:20050 
    --- End of 1c8dea71-4784-11e8-8347-060555473160 ---
    --- 48665f04-4775-11e8-8ad2-060555473160 ---
    States: CONNECTED | CONNECTED
    Network: 10.241.183.245 06:51:cc:67:54:88
    Endpoint: 192.168.66.248:52638
    All Endpoints: 192.168.66.248:52638 35.159.10.202:20032 52.58.220.11:20032 13.250.117.166:20032 54.183.200.212:20031 54.233.167.241:20031 
    Endpoints pool: 192.168.66.248:52638 192.168.122.1:52638 5.57.15.122:52638 35.159.10.202:20032 52.58.220.11:20032 13.250.117.166:20032 54.183.200.212:20031 54.233.167.241:20031 
    --- End of 48665f04-4775-11e8-8ad2-060555473160 ---
Bootstrap nodes:
Hash: swarm-f0ff0fbf-5eff-4662-afc4-a756ea684a4d
ID: 80901b76-478a-11e8-86d0-060555473160
UDP Port: 42463
Network interfaces: 192.168.121.54 192.168.88.248 172.21.107.251 172.21.107.252 172.18.19.252 172.24.124.252 172.20.84.252 172.20.84.251 10.10.10.254 10.231.109.1 10.241.183.1 
P2P Interface p2p4, HW Addr: 06:36:1b:95:1c:13, IP: 10.18.17.1
Proxies: 54.183.200.212:40622/20038 35.159.10.202:40622/20040 54.233.167.241:40622/20038 13.250.117.166:40622/20026 52.58.220.11:40622/20040 
Peers:
    --- a2c841cc-477a-11e8-8721-060555473160 ---
    States: CONNECTED | CONNECTED
    Network: 10.18.17.245 00:ff:1c:50:b5:5b
    Endpoint: 192.168.66.249:56213
    All Endpoints: 192.168.66.249:56213 35.159.10.202:20063 54.183.200.212:20057 52.58.220.11:20063 54.233.167.241:20057 13.250.117.166:20055 
    Endpoints pool: 192.168.56.1:56213 172.4.4.100:56213 172.8.4.100:56213 172.7.4.100:56213 172.6.4.100:56213 172.3.4.100:56213 172.5.4.100:56213 172.9.4.100:56213 192.168.66.249:56213 5.57.15.122:56213 54.183.200.212:20057 35.159.10.202:20063 54.233.167.241:20057 13.250.117.166:20055 52.58.220.11:20063 
    --- End of a2c841cc-477a-11e8-8721-060555473160 ---
Bootstrap nodes:
Hash: swarm-cbfeac1c-6245-402c-b31b-d3b5560ac3c6
ID: 33759413-47a6-11e8-8f41-060555473160
UDP Port: 59718
Network interfaces: 192.168.121.54 192.168.88.248 172.21.107.251 172.21.107.252 172.18.19.252 172.24.124.252 172.20.84.252 172.20.84.251 10.10.10.254 10.231.109.1 10.241.183.1 10.18.17.1 
P2P Interface p2p2, HW Addr: 06:b0:4d:fc:46:9f, IP: 10.89.21.1
Proxies: 52.58.220.11:40622/20030 54.183.200.212:40622/20029 35.159.10.202:40622/20030 54.233.167.241:40622/20029 13.250.117.166:40622/20033 
Peers:
    --- d5cb1021-47a6-11e8-8849-060555473160 ---
    States: CONNECTED | CONNECTED
    Network: 10.89.21.245 06:04:e9:02:86:48
    Endpoint: 172.16.0.248:41986
    All Endpoints: 172.16.0.248:41986 52.58.220.11:20035 35.159.10.202:20036 54.183.200.212:20041 54.233.167.241:20041 13.250.117.166:20046 
    Endpoints pool: 172.16.0.248:41986 192.168.122.1:41986 172.28.128.1:41986 5.57.15.122:41986 52.58.220.11:20035 35.159.10.202:20036 54.183.200.212:20041 54.233.167.241:20041 13.250.117.166:20046 
    --- End of d5cb1021-47a6-11e8-8849-060555473160 ---
    --- 32fd5922-47a7-11e8-873f-060555473160 ---
    States: CONNECTED | CONNECTED
    Network: 10.89.21.246 00:ff:7a:1d:5f:56
    Endpoint: 172.16.0.234:52470
    All Endpoints: 172.16.0.234:52470 52.58.220.11:20042 35.159.10.202:20042 54.183.200.212:20047 54.233.167.241:20047 13.250.117.166:20047 
    Endpoints pool: 192.168.56.1:52470 172.28.128.1:52470 172.16.0.234:52470 172.6.4.100:52470 172.8.4.100:52470 172.9.4.100:52470 172.7.4.100:52470 5.57.15.122:52470 52.58.220.11:20042 35.159.10.202:20042 54.183.200.212:20047 54.233.167.241:20047 13.250.117.166:20047 
    --- End of 32fd5922-47a7-11e8-873f-060555473160 ---
root@subutai:~# subutai-master.p2p show
06:36:1b:95:1c:13   10.18.17.1  swarm-f0ff0fbf-5eff-4662-afc4-a756ea684a4d
06:b0:4d:fc:46:9f   10.89.21.1  swarm-cbfeac1c-6245-402c-b31b-d3b5560ac3c6
06:0b:39:0b:93:7d   10.231.109.1    swarm-3ac920d7-c127-4f5a-8052-915469b22617
06:77:11:04:a6:47   10.241.183.1    swarm-cd2c3df9-ab6c-4881-9082-c40d78d7d576
root@subutai:~#

**Comment by AlinaPenkina** [comment]
From bazaar side it shows 5 envs.

**Comment by crioto** [comment]
Turns out this was snap update problem

**Comment by AlinaPenkina** [comment]
I checked this several times on several peers, after restarting p2p on peer, quantity of swarm is stable and always the same.

**Comment by amangeldizhusubaliev** [comment]
done
