### ISSUE TITLE
P2P should restore active connections after restart or crash.

### ISSUE THREAD

**Issue by soffokl** [subutai-io/p2p#8]
P2P daemon works only with active connections and does not store it somewhere. And in case if service was restarted or crashed, P2P daemon after restart has clear configuration and does not restore previous connections.

It will be incredibly useful if P2P daemon will restore all active connection after start.

**Comment by crioto** [comment]
Now save and restore functionality has been added. New argument has been added:
```
  -save string
    	Path to restore file
```
This argument should be specified at daemon startup (along with a -daemon argument).
