### ISSUE TITLE
Implement "auto" value for automatic IP configuration

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#816]
Currently we support static IP or "dhcp" value for `--ip` option. We need to implement `auto`, that will configure interfaces later, after successfully establishing connection with peers. In case when picked IP is already taken by someone this option will automatically reconfigure interface to use next free IP

**Comment by crioto** [comment]
In order to test this case it's better to create separate environment. 

Make sure, that Control Center is disabled on every computer where you test this feature. After you make sure that CC isn't running, restart p2p daemon manually: On windows via `services.msc`, on Linux: `sudo systemclt restart subutai-p2p.service`, on macos: `sudo launchctl unload /Library/LaunchDaemons/io.subutai.p2p.daemon.plist` and `sudo launchctl load /Library/LaunchDaemons/io.subutai.p2p.daemon.plist`
After you did restart p2p make sure that it was restarting by checking Uptime in `p2p debug` output.

Now, on a few different computers you need to start manual p2p connection to your fresh env:
`p2p start -ip auto -hash <environment_hash> -key <environment_key>`
You need to replace <environment_hash> and <environment_key> with data from https://bazaar.subutai.io/rest/v1/tray/environments. Make sure that you use right env!

Expected result: all your peers can ping each other. Use `p2p debug` and see `Peers:` section to lookup IPs: 
```
Peers:
	--- be0a3d6b-f38e-11e8-8c5a-d8cb8a37cf4b ---
	States: CONNECTED | CONNECTED
	Network: 10.100.10.1 06:0d:ba:4c:f7:a6
	Endpoint: 10.10.148.30:34896
	All Endpoints: 10.10.148.30:34896 [13] 85.93.91.135:20142 [206] 62.138.0.66:20151 [207]
Stats: [C: 0] [R: 0] [HP: 0] [CDelta: 16] [RDelta: 0]
	Endpoints pool: 10.10.148.30:34896 60.51.117.194:34896 85.93.91.135:20142 62.138.0.66:20151
	--- End of be0a3d6b-f38e-11e8-8c5a-d8cb8a37cf4b ---
```
Look at the `Network: 10.100.10.1 06:0d:ba:4c:f7:a6` - `10.100.10.1` is IP that you need to ping to test if p2p works. Of course in your case IP will be different. 

If ping works in all directions - that means test passed. 
For your convenience you can run this test from all 3 different operating systems at the same time, so your environment will contain 1 peer and 3 other participants will be your clients

**Comment by kurmanbekova6** [comment]
Followed the steps described above:
![screenshot_21](https://user-images.githubusercontent.com/9501291/49418717-6f293180-f738-11e8-86c8-6eadf1a37dad.png)
![screenshot from 2018-12-04 10-13-15](https://user-images.githubusercontent.com/9501291/49418729-7ea87a80-f738-11e8-83f2-61a9ee2184fa.png)
![screen shot 2018-12-04 at 10 15 01](https://user-images.githubusercontent.com/9501291/49418730-80723e00-f738-11e8-8f31-75f1faa10e4d.png)
Tested in master

**Comment by kurmanbekova6** [comment]
Output from Linux (prod)
![screenshot from 2018-12-04 17-38-30](https://user-images.githubusercontent.com/9501291/49439518-72c9c080-f7eb-11e8-8d86-9e92087292fd.png)

**Comment by kurmanbekova6** [comment]
Output from Linux (prod)
![screenshot from 2018-12-04 17-48-07](https://user-images.githubusercontent.com/9501291/49440023-c8eb3380-f7ec-11e8-85c1-525bc83dac64.png)

**Comment by kurmanbekova6** [comment]
![screenshot_24](https://user-images.githubusercontent.com/9501291/49440156-c4386800-f777-11e8-9575-54bddbe9f677.png)

**Comment by kurmanbekova6** [comment]
![screen shot 2018-12-04 at 17 52 26](https://user-images.githubusercontent.com/9501291/49440262-5af33c00-f7ed-11e8-9fe7-7a67c1413061.png)
Tested in prod
