### ISSUE TITLE
 Failed to properly configure TAP device

### ISSUE THREAD

**Issue by slavakimod** [subutai-io/p2p#84]
**System Configuration**
Windows 10 x64
OpenVPN 2.3.10-l601
TAP Windows 9.21.1

**P2P Log**
[INFO] 2016/03/14 19:33:39 Starting RPC Listener on 52523 port
[INFO] 2016/03/14 19:33:44 Generate MAC for TAP device: 06:fa:b9:17:8c:9e
[INFO] 2016/03/14 19:33:44 Looking for available network interfaces
[INFO] 2016/03/14 19:33:44 Interface Ethernet: 192.168.0.100/16. Type: Global Unicast. Saving
[INFO] 2016/03/14 19:33:44 Interface Loopback Pseudo-Interface 1: ::1/28. Type: Loopback. Ignoring
[INFO] 2016/03/14 19:33:44 Interface Loopback Pseudo-Interface 1: 127.0.0.1/16. Type: Loopback. Ignoring
[INFO] 2016/03/14 19:33:44 1 interfaces were saved
[INFO] 2016/03/14 19:33:44 No AES key were provided. Traffic encryption is disabled
[ERROR] 2016/03/14 19:33:44 Failed to load config: open config.yaml: The system cannot find the file specified.
[INFO] 2016/03/14 19:33:44 Acquired control over TAP interface: Ethernet 2
[INFO] 2016/03/14 19:33:44 vptp1 TAP Device created
[INFO] 2016/03/14 19:33:44 Configuring Ethernet 2. IP: 10.10.10.1 Mask: 255.255.255.0
[INFO] 2016/03/14 19:33:44 Executing: netsh interface ip set address "Ethernet 2" static 10.10.10.1 255.255.255.0
[ERROR] 2016/03/14 19:33:44 Failed to properly configure TAP device with netsh: exit status 1
[INFO] 2016/03/14 19:33:44 Started UDP Listener at port 51721
[INFO] 2016/03/14 19:33:44 DHT operating in CLIENT mode
[INFO] 2016/03/14 19:33:44 Connecting to a router dht1.subut.ai:6881
[INFO] 2016/03/14 19:33:44 Ready to peer discovery via dht1.subut.ai:6881 [52.34.217.204:6881]
[INFO] 2016/03/14 19:33:44 Handshaked. Starting listener
[INFO] 2016/03/14 19:33:44 Bootstraping via 52.34.217.204:6881

**Comment by crioto** [comment]
Fixed in master
