### ISSUE TITLE
Change path of p2p binary on Linux

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#849]
Currently we are placing p2p binary into `/opt/subutai/bin/p2p` and this needs to be changed to make our p2p debian package be more Linux-friendly. 
p2p debian package will place p2p binary into `/usr/bin` and will be available by this apth: `/usr/bin/p2p`.
@Erkin97 should prepare CC to handle these changes accordingly.

**Comment by lbthomsen** [comment]
well it'll be in the path then so simply "p2p"

**Comment by lbthomsen** [comment]
I am right that apart from the systemd stuff that's the only file in p2p package right?

**Comment by crioto** [comment]
It have systemd unit file and p2p binary only, correct

**Comment by AlinaPenkina** [comment]
Done.
