### ISSUE TITLE
P2P panic if you have running OpenVPN connection (and vise-versa)

### ISSUE THREAD

**Issue by slavakimod** [subutai-io/p2p#85]
**Behavior**
If you have P2P running - you cannot start any OpenVPN connection
If you have any active OpenVPN connections you are getting panic on command p2p start -ip ...

**Log of exception**
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x4c805f]

goroutine 7 [running]:
github.com/subutai-io/p2p/lib.openDevice(0xc082128d00, 0x5, 0xc08202b468, 0x0, 0x0)
        C:/Projects/go/src/github.com/subutai-io/p2p/lib/tuntap_windows.go:147 +0x25f
github.com/subutai-io/p2p/lib.Open(0xc082128d00, 0x5, 0x1, 0x8b1680, 0x0, 0x0)
        C:/Projects/go/src/github.com/subutai-io/p2p/lib/tuntap_windows.go:258 +0x3e
main.(*PTPCloud).AssignInterface(0xc082062c60, 0xc082009e30, 0xa, 0xc08210e3e0, 0x11, 0xc082009e50, 0xd, 0xc082128d00, 0x5, 0x0, ...)
        C:/Projects/go/src/github.com/subutai-io/p2p/p2p.go:80 +0x3ef
main.p2pmain(0xc082009e30, 0xa, 0xc082009e50, 0xd, 0xc08210e3e0, 0x11, 0xc082128d00, 0x5, 0x0, 0x0, ...)
        C:/Projects/go/src/github.com/subutai-io/p2p/p2p.go:283 +0x11a3
main.(*Procedures).Run(0xc0820d6450, 0xc082070dc0, 0xc08210e2c0, 0x0, 0x0)
        C:/Projects/go/src/github.com/subutai-io/p2p/instance.go:201 +0x3bf
reflect.Value.call(0x801880, 0x883510, 0x13, 0x8bba50, 0x4, 0xc08202bed8, 0x3, 0x3, 0x0, 0x0, ...)
        c:/go/src/reflect/value.go:432 +0x1211
reflect.Value.Call(0x801880, 0x883510, 0x13, 0xc08202bed8, 0x3, 0x3, 0x0, 0x0, 0x0)
        c:/go/src/reflect/value.go:300 +0xb8
net/rpc.(*service).call(0xc0820d0700, 0xc0820d0200, 0xc082009700, 0xc0820dc280, 0xc082003ae0, 0x76e4e0, 0xc082070dc0, 0x16, 0x76e480, 0xc08210e2c0, ...)
        c:/go/src/net/rpc/server.go:383 +0x1c8
created by net/rpc.(*Server).ServeCodec
        c:/go/src/net/rpc/server.go:477 +0x4b3

goroutine 1 [sleep]:
time.Sleep(0x12a05f200)
        c:/go/src/runtime/time.go:59 +0x107
main.Daemon(0x8bb4b8, 0x5, 0x0, 0x0, 0x0, 0x0)
        C:/Projects/go/src/github.com/subutai-io/p2p/main.go:339 +0x641
main.main()
        C:/Projects/go/src/github.com/subutai-io/p2p/main.go:118 +0x162e

goroutine 17 [syscall]:
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
        c:/go/src/os/signal/signal_unix.go:28 +0x3e

goroutine 18 [IO wait]:
net.runtime_pollWait(0x2a312b0, 0x72, 0xc0820096b0)
        c:/go/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc0820342f0, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc0820d8030, 0xc0820341e0, 0x8c5f30, 0x8, 0xc082003a60, 0xc08201ad80, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:182 +0x177
net.(*netFD).acceptOne(0xc082034180, 0xc0820841c0, 0x2, 0x2, 0xc0820341e0, 0x220000, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:564 +0x26c
net.(*netFD).accept(0xc082034180, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:594 +0x173
net.(*TCPListener).AcceptTCP(0xc0820d8040, 0xc0820ede60, 0x0, 0x0)
        c:/go/src/net/tcpsock_posix.go:254 +0x54
net.(*TCPListener).Accept(0xc0820d8040, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/net/tcpsock_posix.go:264 +0x44
net/http.(*Server).Serve(0xc0820f0060, 0x2a30308, 0xc0820d8040, 0x0, 0x0)
        c:/go/src/net/http/server.go:1887 +0xba
net/http.Serve(0x2a30308, 0xc0820d8040, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/net/http/server.go:1765 +0x8c
created by main.Daemon
        C:/Projects/go/src/github.com/subutai-io/p2p/main.go:323 +0x55a

goroutine 19 [chan receive]:
main.Daemon.func1(0xc0820f0000)
        C:/Projects/go/src/github.com/subutai-io/p2p/main.go:332 +0x85
created by main.Daemon
        C:/Projects/go/src/github.com/subutai-io/p2p/main.go:337 +0x62e

goroutine 6 [IO wait]:
net.runtime_pollWait(0x2a311f0, 0x72, 0xc082009e80)
        c:/go/src/runtime/netpoll.go:157 +0x67
net.(*pollDesc).Wait(0xc0820348f0, 0x72, 0x0, 0x0)
        c:/go/src/net/fd_poll_runtime.go:73 +0x41
net.(*ioSrv).ExecIO(0xc0820d8030, 0xc0820347e0, 0x8bdbc8, 0x7, 0x9847c8, 0xc082078201, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:182 +0x177
net.(*netFD).Read(0xc082034780, 0xc08210a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/fd_windows.go:463 +0x17e
net.(*conn).Read(0xc082024080, 0xc08210a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        c:/go/src/net/net.go:172 +0xeb
bufio.(*Reader).fill(0xc08200e420)
        c:/go/src/bufio/bufio.go:97 +0x1f0
bufio.(*Reader).Read(0xc08200e420, 0xc0820096e0, 0x1, 0x9, 0x0, 0x0, 0x0)
        c:/go/src/bufio/bufio.go:207 +0x267
io.ReadAtLeast(0x3a4a50, 0xc08200e420, 0xc0820096e0, 0x1, 0x9, 0x1, 0x0, 0x0, 0x0)
        c:/go/src/io/io.go:298 +0xed
io.ReadFull(0x3a4a50, 0xc08200e420, 0xc0820096e0, 0x1, 0x9, 0xc0820fd000, 0x0, 0x0)
        c:/go/src/io/io.go:316 +0x69
encoding/gob.decodeUintReader(0x3a4a50, 0xc08200e420, 0xc0820096e0, 0x9, 0x9, 0x0, 0x1, 0x0, 0x0)
        c:/go/src/encoding/gob/decode.go:121 +0x99
encoding/gob.(*Decoder).recvMessage(0xc082078280, 0xc08202f408)
        c:/go/src/encoding/gob/decoder.go:76 +0x65
encoding/gob.(*Decoder).decodeTypeSequence(0xc082078280, 0x984e00, 0xc082078280)
        c:/go/src/encoding/gob/decoder.go:140 +0x4e
encoding/gob.(*Decoder).DecodeValue(0xc082078280, 0x771ae0, 0xc08210e2e0, 0x16, 0x0, 0x0)
        c:/go/src/encoding/gob/decoder.go:208 +0x164
encoding/gob.(*Decoder).Decode(0xc082078280, 0x771ae0, 0xc08210e2e0, 0x0, 0x0)
        c:/go/src/encoding/gob/decoder.go:185 +0x290
net/rpc.(*gobServerCodec).ReadRequestHeader(0xc0820878f0, 0xc08210e2e0, 0x0, 0x0)
        c:/go/src/net/rpc/server.go:403 +0x58
net/rpc.(*Server).readRequestHeader(0xc0820d0200, 0x3a4aa0, 0xc0820878f0, 0x0, 0x0, 0xc08210e2e0, 0xc08202f700, 0x0, 0x0)
        c:/go/src/net/rpc/server.go:576 +0x97
net/rpc.(*Server).readRequest(0xc0820d0200, 0x3a4aa0, 0xc0820878f0, 0xc0820d0200, 0xc082009700, 0xc0820dc280, 0x0, 0x0, 0x0, 0x0, ...)
        c:/go/src/net/rpc/server.go:543 +0x92
net/rpc.(*Server).ServeCodec(0xc0820d0200, 0x3a4aa0, 0xc0820878f0)
        c:/go/src/net/rpc/server.go:462 +0x93
net/rpc.(*Server).ServeConn(0xc0820d0200, 0x3a49f0, 0xc082024080)
        c:/go/src/net/rpc/server.go:454 +0x4f5
net/rpc.(*Server).ServeHTTP(0xc0820d0200, 0x3a4940, 0xc0820b5810, 0xc0820842a0)
        c:/go/src/net/rpc/server.go:694 +0x50a
net/http.(*ServeMux).ServeHTTP(0xc082086d80, 0x3a4940, 0xc0820b5810, 0xc0820842a0)
        c:/go/src/net/http/server.go:1699 +0x184
net/http.serverHandler.ServeHTTP(0xc0820f0060, 0x3a4940, 0xc0820b5810, 0xc0820842a0)
        c:/go/src/net/http/server.go:1862 +0x1a5
net/http.(*conn).serve(0xc0820b5760)
        c:/go/src/net/http/server.go:1361 +0xbf5
created by net/http.(*Server).Serve
        c:/go/src/net/http/server.go:1910 +0x3fd

**Comment by crioto** [comment]
Currently p2p application conflicts with OpenVPN software under Windows. It will not panic anymore, but will gently disable existing openvpn interfaces.
