### ISSUE TITLE
Error appears during stop p2p in service list

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/p2p#898]
Windows 10
Error appears during stop p2p in service list
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/918fcfd9-82cb-4cc5-94b5-4072fb1bf0a9)

**Comment by AlinaPenkina** [comment]
And this:

![image](https://user-images.githubusercontent.com/34295807/39296774-99fce72c-4963-11e8-892f-49c699af4af0.png)

**Comment by TerGunter** [comment]
![image](https://user-images.githubusercontent.com/38347277/39618986-eb8e8bc8-4fa7-11e8-8f19-f5c29f2fe1a9.png)
i still face this error. Win10

**Comment by crioto** [comment]
Didn't appear for a long time.
