### ISSUE TITLE
Determine best proxy

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#907]
Instead of using all possible proxies we need to determine one single proxy that have better connection quality (less latency value). For this purpose daemon will keep list of all known proxies and use ICMP to determine latency value of each. When instance requests proxies it will just use the best one (or maybe two as a backup)

**Comment by kurmanbekova6** [comment]
```Proxies: 85.25.210.145:40622/20004 [108] 85.93.89.182:40622/20027 [108]```
Fixed in Master

**Comment by kurmanbekova6** [comment]
`Proxies: 85.93.91.135:40622/20125 [96] `
Tested in prod.
