### ISSUE TITLE
Unable to uninstall p2p because it's running in Task Manager

### ISSUE THREAD

**Issue by ibragim13kz** [subutai-io/p2p#908]
Can not uninstall p2p from control panel as well as from applications because I need to stop it in task manager before. Win 10. 
![screenshot_11](https://user-images.githubusercontent.com/33474101/39416977-f5133ee2-4c72-11e8-9939-201f9826d037.png)
![screenshot_12](https://user-images.githubusercontent.com/33474101/39416976-f512b148-4c72-11e8-9285-c3cc09ff8bb1.png)

**Comment by AlinaPenkina** [comment]
Done.
