### ISSUE TITLE
p2p doesn't start keep alive session

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#926]
Keep alive functionality got broke after latest changes related to removal of DHT flag.

**Comment by amangeldizhusubaliev** [comment]
Didn't face "starting keep alive session" in my logs. Will continue tomorrow.

**Comment by amangeldizhusubaliev** [comment]
Should have envs in order to face this message

**Comment by amangeldizhusubaliev** [comment]
fixed on master.

**Comment by AlinaPenkina** [comment]
Done
