### ISSUE TITLE
p2p lost proxies.

### ISSUE THREAD

**Issue by Shahrizada** [subutai-io/p2p#931]
MacOS

2 out of 5 envs are stuck in "connecting" state.

p2p debug:

`Last login: Mon May  7 11:37:15 on ttys000
-bash: nexport: command not found
Shahris-Air:~ shahrizadakarasulu$ p2p debug
Version: 6.3.3-master Build: 6.3.3-41-g56d259d
Uptime: 61 h 43 m 51 s
Number of gouroutines: 45
Bootstrap nodes information:
  52.58.220.11:6881 Rx: 16769823247 Tx: 70831961
Instances information:
Bootstrap nodes:
Hash: swarm-c2713ee3-bdd9-4f3f-bf8c-dd1ec554457d
ID: 7ad41bee-51ba-11e8-82d0-060555473160
UDP Port: 63097
Network interfaces: 192.168.66.242 
P2P Interface tap4, HW Addr: 06:88:ac:2c:93:06, IP: 10.62.149.246
Proxies: 52.58.220.11:40622/20010 
Peers:
Bootstrap nodes:
Hash: swarm-dbaaf463-7fbb-4d8b-b2d1-8c41e0fe1530
ID: 8efda204-51b6-11e8-8af9-060555473160
UDP Port: 55579
Network interfaces: 192.168.66.242 
P2P Interface tap5, HW Addr: 06:e3:f8:3c:70:d5, IP: 10.41.123.245
Proxies: 52.58.220.11:40622/20008 
Peers:
	--- 51c315fe-50f1-11e8-882e-060555473160 ---
	States: CONNECTED | CONNECTED
	Network: 10.41.123.1 06:dd:6c:11:77:3f
	Endpoint: 192.168.88.250:46795
	All Endpoints: 192.168.88.250:46795 52.58.220.11:20026 
	Endpoints pool: 192.168.88.250:46795 5.57.13.168:46795 35.159.10.202:20025 52.58.220.11:20026 54.183.200.212:20025 13.250.117.166:20030 54.233.167.241:20025 
	--- End of 51c315fe-50f1-11e8-882e-060555473160 ---
Bootstrap nodes:
Hash: swarm-536e51ba-e69e-48f5-854b-c4af39315e0c
ID: 8ce681fd-51ba-11e8-8424-060555473160
UDP Port: 50256
Network interfaces: 192.168.66.242 
P2P Interface tap9, HW Addr: 06:08:5e:21:57:ca, IP: 10.165.231.245
Proxies: 52.58.220.11:40622/20012 
Peers:
	--- 05dfd776-4fa3-11e8-86ae-060555473160 ---
	States: INITIALIZING | WAITING_CONNECTION
	No IP assigned
	Endpoints pool: 192.168.88.33:39120 5.57.14.156:39120 35.159.10.202:20019 52.58.220.11:20021 13.250.117.166:20016 54.183.200.212:20016 54.233.167.241:20020 
	--- End of 05dfd776-4fa3-11e8-86ae-060555473160 ---
	--- 52f8149d-50f1-11e8-8702-060555473160 ---
	States: CONNECTED | CONNECTED
	Network: 10.165.231.1 06:b5:21:17:20:f1
	Endpoint: 192.168.88.33:39120
	All Endpoints: 192.168.88.33:39120 52.58.220.11:20019 
	Endpoints pool: 192.168.88.33:39120 5.57.13.168:39120 52.58.220.11:20019 35.159.10.202:20019 54.183.200.212:20017 13.250.117.166:20026 54.233.167.241:20020 
	--- End of 52f8149d-50f1-11e8-8702-060555473160 ---
Bootstrap nodes:
Hash: swarm-86c4ade7-6ca8-47e0-96e8-b9a38960c877
ID: 6e8aea76-51ae-11e8-8ea1-060555473160
UDP Port: 53630
Network interfaces: 192.168.66.242 
P2P Interface tap0, HW Addr: 06:73:4a:f6:2c:8b, IP: 10.45.59.245
Proxies: No proxies in use
Peers:
Bootstrap nodes:
Hash: swarm-72e17ba6-1264-497d-9be0-169b428fa399
ID: cc30b60b-51b8-11e8-8c38-060555473160
UDP Port: 52310
Network interfaces: 192.168.66.242 
P2P Interface tap8, HW Addr: 06:49:84:23:e8:64, IP: 10.189.210.245
Proxies: 52.58.220.11:40622/20014 
Peers:
	--- 48b3a091-50f1-11e8-8747-060555473160 ---
	States: CONNECTED | CONNECTED
	Network: 10.189.210.1 06:7c:3f:63:e8:4c
	Endpoint: 192.168.88.31:41599
	All Endpoints: 192.168.88.31:41599 52.58.220.11:20005 
	Endpoints pool: 192.168.88.31:41599 5.57.13.168:41599 52.58.220.11:20005 
	--- End of 48b3a091-50f1-11e8-8747-060555473160 ---
	--- 0295914d-4fa3-11e8-8013-060555473160 ---
	States: INITIALIZING | WAITING_CONNECTION
	No IP assigned
	Endpoints pool: 192.168.88.31:41599 5.57.14.156:41599 35.159.10.202:20086 52.58.220.11:20086 54.183.200.212:20085 13.250.117.166:20088 54.233.167.241:20085 
	--- End of 0295914d-4fa3-11e8-8013-060555473160 ---
	--- 0b98094f-4f4a-11e8-8c3a-060555473160 ---
	States: INITIALIZING | UNKNOWN
	No IP assigned
	Endpoints pool: 192.168.66.242:52310 77.95.57.233:52310 35.159.10.202:20018 52.58.220.11:20018 54.233.167.241:20020 54.183.200.212:20019 13.250.117.166:20007 
	--- End of 0b98094f-4f4a-11e8-8c3a-060555473160 ---
	--- 7f2c6e6c-507c-11e8-8ccf-060555473160 ---
	States: INITIALIZING | WAITING_CONNECTION
	No IP assigned
	Endpoints pool: 192.168.88.31:41599 5.57.14.156:41599 54.183.200.212:20085 13.250.117.166:20088 35.159.10.202:20086 52.58.220.11:20086 54.233.167.241:20085 
	--- End of 7f2c6e6c-507c-11e8-8ccf-060555473160 ---

Shahris-Air:~ shahrizadakarasulu$ `

https://masterbazaar.subutai.io/rest/v1/tray/environments:
~removed~

**Comment by AlinaPenkina** [comment]
I faced this problem too on Mac. Here are logs and p2p debug from it:

**Comment by crioto** [comment]
Face the same problem on one of production peers: 
```
Proxies:
Peers:
        --- 03691541-723a-11e8-8fc4-067d36744cfc ---
        States: INITIALIZING_CONNECTION | INITIALIZING_CONNECTION
        No IP assigned
        Endpoints pool: 172.7.4.100:61155 158.181.229.159:61155 18.195.241.137:20073
        --- End of 03691541-723a-11e8-8fc4-067d36744cfc ---
        --- 2b013f6f-720b-11e8-8c3a-067d36744cfc ---
        States: WAITING_CONNECTION | REQUESTING_PROXIES
        No IP assigned
        Endpoints pool: 172.16.1.21:53738 192.168.121.1:53738 212.112.122.226:53738 18.195.241.137:20094 13.250.10.232:20093
        --- End of 2b013f6f-720b-11e8-8c3a-067d36744cfc ---
        --- e03d7545-709a-11e8-8a26-067d36744cfc ---
        States: INITIALIZING_CONNECTION | INITIALIZING_CONNECTION
        No IP assigned
        Endpoints pool: 209.126.104.120:59528 18.195.241.137:20134 13.250.10.232:20080
        --- End of e03d7545-709a-11e8-8a26-067d36744cfc ---
        --- 8986f212-7244-11e8-84c7-067d36744cfc ---
        States: WAITING_CONNECTION | REQUESTING_PROXIES
        No IP assigned
        Endpoints pool: 172.16.1.10:55039 212.112.122.226:55039 18.195.241.137:20031 13.250.10.232:20004
        --- End of 8986f212-7244-11e8-84c7-067d36744cfc ---
```

**Comment by AlinaPenkina** [comment]
Done.
