### ISSUE TITLE
Network Coordinate System

### ISSUE THREAD

**Issue by marcoarthur** [subutai-io/p2p#932]
## Problem ##
This Issue is to track work on development of a Network Coordinate System, so we can measure peer's distance. And create a map out of subutai peers.

Based on: http://www.cs.ucsb.edu/~ravenben/classes/276/papers/vivaldi-sigcomm04.pdf
using https://www.consul.io/docs/internals/coordinates.html implementation

## Test ##
Set up a test to see how will be applied the already implemented system that is able to give a map for peer distance. Steps for this is, estimates in WD (work days)

1. We are currently using an implementation that *don't match exactly paper algorithm* so analyze the differences. (  almost done, 2 WD to conclude )
2. Write the smallest app to be deployed in a small set of our own containers (  3  WD )
3. Check scale, deploy it to as many possible (1 WD )

## Report ##
Make a report to explain not only how we can use it, but how it can be deployed with our own p2p (or maybe agent). So we can use this to measure and map network. ( 1/2 WD )

## Presentation ##
Create a presentation to explain details of Vivaldis techinique for network distance and how it can be used (or not if results not satisfact our needs) on subutai cloud ( 1/2 WD or less)

**Comment by crioto** [comment]
Will be handled under #445
