### ISSUE TITLE
Implement PMTU

### ISSUE THREAD

**Issue by crioto** [subutai-io/p2p#954]
When p2p receives a packet with DF (Don't fragment) flag set and its size exceeds MTU we need to send an ICMP response of type 3, code 4 (Destination Unreachable) back to the original sender with specified next-hop MTU value. 
This process is described here: https://tools.ietf.org/html/rfc1191

**Comment by crioto** [comment]
For QA team: 
Setup an environment with two containers on two different peers. SSH into one of the containers and SSH into second container on another peer

**Comment by niclash** [comment]
It also solves the case with a peer-layout of many peers running the same apps. I have blueprint for that,  https://github.com/niclash/subutai-bp-zookeeper, and by selecting 3 or 5 "instances" you trigger the (hopefully now fixed) issue. If not fixed, all except one peer will have "unreachable" in the error log.

**Comment by crioto** [comment]
@niclash unfortunately problem seems to be bigger, than just on p2p level. We are investigating it and I will inform you about it later.

**Comment by crioto** [comment]
@niclash During further experiments @lbthomsen confirmed that this problem is above p2p, so we will start working on implementation of custom MTU on container level very soon.

@AlinaPenkina to test this issue properly you need to SSH between two peers (not containers!) over p2p link. If everything works ok you will be able to SSH and in logs you will see three messages in the following order:
`Received packet that exceeds MTU: %d [Expected: %d]`
`Received IPv4 message with DF flag set`
`Sending Destination Unreachable ICMP response`

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by AlinaPenkina** [comment]
Done.
