### ISSUE TITLE
p2p isn't starting after rebooting of PC.

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/p2p#979]
Windows 10
After updating of Windows my net interfaces became turned off. I turned on them manually. After this p2p daemon doesn't start automatically.
It happened on my office PC and seems at home too. But I tested on virtual Windows 10 and didn't face this problem. So I am creating issue to not forget about it and observe it.

**Comment by crioto** [comment]
@AlinaPenkina Thanks. I will search for net-related fixes in recent windows updates

**Comment by ibragim13kz** [comment]
Reproduced this case (did reboot), and also faced this problem. P2P doesn't launch itself, also it's not running in Services.

**Comment by crioto** [comment]
@ibragim13kz you can launch it manually?

**Comment by ibragim13kz** [comment]
@crioto Yes, I can launch it manually. But now I observe swaps. I mean, before I didn't see those swaps today.

**Comment by crioto** [comment]
Ok, thanks. Let’s investigate this more carefully and determine why this happens only on some machines

**Comment by AlinaPenkina** [comment]
Done.

**Comment by AlinaPenkina** [comment]
done.
