### ISSUE TITLE
p2p daemon crash after creating instance

### ISSUE THREAD

**Issue by soffokl** [subutai-io/p2p#99]
After creating Subutai crosspeer environment, p2p daemon crash and connection cannot be established. 

* 2xRH in LAN;
* encryption enabled;
* One RH with static IP, one with dynamic.

[p2p.txt](https://github.com/subutai-io/p2p/files/189164/p2p.txt)
[p2p.txt](https://github.com/subutai-io/p2p/files/189167/p2p.txt)

Logs from crosspeer initiator:
[karaflogs2016-03-25 13-10-43.txt](https://github.com/subutai-io/p2p/files/189169/karaflogs2016-03-25.13-10-43.txt)

**Comment by crioto** [comment]
This is due your interface name - control_network. You need to shrink interface name in order to get it working. 15 symbols - it's a system limitation. 
I've tried with ctrl_net - it works.
